square/workflow

sample-android-app/src/main/java/com/squareup/sample/authgameapp/ShellState.kt, sample-game-common/src/main/java/com/squareup/sample/tictactoe/RunGameState.kt, workflow-core/src/main/java/com/squareup/workflow/Delegating.kt, workflow-core/src/main/java/com/squareup/workflow/Worker.kt, workflow-core/src/main/java/com/squareup/workflow/WorkflowPool.kt, workflow-core/src/test/java/com/squareup/workflow/ComposedReactorIntegrationTest.kt, workflow-core/src/test/java/com/squareup/workflow/WorkerTest.kt, workflow-core/src/test/java/com/squareup/workflow/WorkflowPoolTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/WorkflowPoolIntegrationTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/ComposedReactorIntegrationTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkerIntegrationTest.kt
This renaming is required in order to be clearer that it's a workflow-related function.
Closes issue: https://github.com/square/workflow/issues/17
=> Rename makeId functions to makeWorkflowId

workflow-core/src/main/java/com/squareup/workflow/WorkflowPool.kt, workflow-core/src/test/java/com/squareup/workflow/WorkflowPoolTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowPoolIntegrationTest.kt
=> Fix workflow pool race between workflow result reporting and removal.

workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, workflow-core/src/main/java/com/squareup/workflow/WorkflowOperators.kt, workflow-core/src/test/java/com/squareup/workflow/CoroutineWorkflowTest.kt, workflow-core/src/test/java/com/squareup/workflow/WorkflowOperatorsTest.kt
* 9c879cd Fix #69 by correctly implementing switchMapState operator.
* e304784 Fix #71 by cancelling upstream workflow when mapResult workflow is cancelled.
* 1876788 Move the workflow operators into their own file and write unit tests.
=> Fix workflow operators

workflow-core/src/main/java/com/squareup/workflow/WorkflowOperators.kt, workflow-core/src/test/java/com/squareup/workflow/WorkflowOperatorsTest.kt, workflow-rx2/src/main/java/com/squareup/workflow/rx2/WorkflowOperators.kt, workflow-rx2/src/main/java/com/squareup/workflow/rx2/Workflows.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowOperatorsTest.kt
Also fixed a bug in core `switchMapState` where the downstream didn't get cancelled when the transformed workflow's state was cancelled.
=> Introduce a switchMapState variant that takes a lambda returning an Rx2 Observable (closes #53).

gradle.properties
This makes running lint on our multiple android modules so much faster.
=> Enable parallel builds.

sample-game-common/src/test/java/com/squareup/sample/tictactoe/TakeTurnsReactorTest.kt, workflow-rx2/src/main/java/com/squareup/workflow/rx2/EventChannel.kt, workflow-test/README.md, workflow-test/src/main/java/com/squareup/workflow/test/Assertions.kt, workflow-test/src/main/java/com/squareup/workflow/test/rx2/EventChannels.kt
Also suppresses some warnings, and organizes the test code with better packages and file names.
=> Move the event channel test helper to the test module.

sample-android-app/src/main/java/com/squareup/sample/authgameapp/ShellRenderer.kt, sample-game-common/src/main/java/com/squareup/sample/tictactoe/RunGameRenderer.kt, workflow-core/src/main/java/com/squareup/workflow/Renderer.kt
Allows this:
```
return TakeTurnsRenderer
.render(state.takingTurns, workflows)
.let { MainAndModalScreen(it) }
```
instead of this:
```
return TakeTurnsRenderer
.render(state.takingTurns.state, workflows.input(state.takingTurns), workflows)
.let { MainAndModalScreen(it) }
```
Closes #103
=> Adds two arg Render.render() extension.

workflow-core/src/main/java/com/squareup/workflow/Reaction.kt
Several internal slack messages showed developers are getting scared and confused by "basically a monad". The sentence that follows is super clear, so seems worth sticking to that?
=> Removed "Basically a monad"

build.gradle, sample-android-app/src/main/java/com/squareup/sample/authgameapp/ShellActivity.kt, sample-android-app/src/main/java/com/squareup/sample/authgameapp/ShellCoordinator.kt, sample-auth-android/src/main/java/com/squareup/sample/authworkflow/android/AuthViewBindings.kt, sample-game-android/src/main/java/com/squareup/sample/tictactoe/android/GameOverCoordinator.kt, sample-game-android/src/main/java/com/squareup/sample/tictactoe/android/TicTacToeViewBindings.kt, viewregistry-android/build.gradle, viewregistry-android/src/main/java/com/squareup/viewregistry/BackStackEffect.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/BackStackFrameLayout.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/BuilderBinding.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/LayoutBinding.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/NoEffect.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/PushPopEffect.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/ViewBinding.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/ViewRegistry.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/ViewStateStack.kt, viewregistry/src/main/java/com/squareup/viewregistry/BackStackScreen.kt
`ViewRegistry` now provides `BackStackEffect`s in addition to `ViewBinding`s. Rather than go crazy with a commit message here, I'm hoping you'll look at the new class doc and tell me if it gets the big picture across.
=> Introduces BackStackEffect

viewregistry-android/src/main/java/com/squareup/viewregistry/BackStackEffect.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/BackStackFrameLayout.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/NoEffect.kt, viewregistry-android/src/main/java/com/squareup/viewregistry/PushPopEffect.kt
One less mistake for effect authors to make becomes one more mistake for
container authors -- we're probably going to write more effects than
containers.
Closes #134.
=> Effects are no longer responsible for saving the outgoing view.

kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/authworkflow/SecondFactorCoordinator.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/panel/PanelContainer.kt, kotlin/samples/tictactoe/android/src/main/res/layout/second_factor_layout.xml, kotlin/samples/tictactoe/android/src/main/res/values/ids.xml, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthEvent.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthReactor.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthRenderer.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/SecondFactorScreen.kt, kotlin/viewregistry-android/src/main/java/com/squareup/viewregistry/AlertContainer.kt, kotlin/viewregistry-android/src/main/java/com/squareup/viewregistry/ModalContainer.kt, kotlin/viewregistry-android/src/main/java/com/squareup/viewregistry/ModalViewContainer.kt, kotlin/viewregistry-android/src/main/java/com/squareup/viewregistry/backstack/BackStackContainer.kt
ModalContainer now implements `onSaveInstanceState()` and `onRestoreInstanceState()`.
Holds onto the most recently restored state, and applies it to the first shown base
view and dialog stacks.
Note also that ModalContainer subclasses and BackStackContainer must have their
`View.id` set in order to participate in view persistence.
Gives the 2fa screen a back button so that we can exercise popping
BackStackContainer again.
Closes #145
=> ModalContainer play nice with Android view persistence.

kotlin/workflow-core/build.gradle, kotlin/workflow-host/build.gradle, kotlin/workflow-rx2/build.gradle, kotlin/workflow-testing/build.gradle
I had bumped it when importing the rewrite, for no particular reason, but don't want to
change transitive deps in 0.8.0 because there's enough things going on.
=> Revert kotlin stdlib bump from jdk6 to jdk7.

Workflow.podspec
Adding a minimum cocoapods version is done as a courtesy for anyone not running the latest beta (to make it clear why the podspec seems broken)
=> Add minimum cocoapods version to podspec

.travis.yml, Package.swift, Workflow.podspec
ReactiveSwift 5.0.0 adds Swift 5 support (meaning that we can adopt Xcode 10.2 without a bunch of warnings coming out of our dependencies)
=> Update ReactiveSwift to 5.0.0

kotlin/build.gradle
This reverts the kotlin version change in commit 8fe6d9d75fdf7a5ddf840d72964d0e5496444ab6.
Turns out 1.2.71 has a bug that causes desugaring to fail on Android.
Supposed to be fixed in 1.3.
We upgraded to 1.2.71 to fix an issue with mismatched transitive deps
internally, a problem to which we've found a different workaround until
we can upgrade to 1.3 (#35).
=> Revert "Bumps kotlin version to 1.2.71"

.gitignore, .travis.yml, swift/Samples/SampleApp/Configuration/Info.plist, swift/Samples/SampleApp/Podfile, swift/Samples/SampleApp/Podfile.lock, swift/Samples/SampleApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json, swift/Samples/SampleApp/Resources/Assets.xcassets/Contents.json, swift/Samples/SampleApp/Resources/Base.lproj/LaunchScreen.storyboard, swift/Samples/SampleApp/SampleApp.xcodeproj/project.pbxproj, swift/Samples/SampleApp/SampleApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata, swift/Samples/SampleApp/SampleApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, swift/Samples/SampleApp/Sources/AppDelegate.swift, swift/Samples/SampleApp/Sources/ViewController.swift
- A sample app will be useful.
- Cocoapods does not support the use of multiple local podspecs for `pod lib lint`. This means that we need a `Podfile` to pull all of this together as we add subsequent Swift libraries.
- We can't rely on Swift Package Manager as the next library to be added imports `UIKit` (SPM has no support for system SDKs).
=> Add empty Swift sample app (and update Cocoapods tests to use the integrated sample app)

kotlin/workflow-core/src/main/java/com/squareup/workflow/EventHandler.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/RealWorkflowContext.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/RealWorkflowContextTest.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/SubscriptionsTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowContextsTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt
This also means we can get rid of the separate `makeUnitSink` function, because we can
just define an override `invoke` for `EventHandler<Unit>`.
Closes #206 and closes #203.
=> Rename makeSink to onEvent, make EventHandler type.

kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/mainactivity/MainComponent.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflowTest.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflows.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/RealWorkflowContext.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/WorkflowId.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/RealWorkflowContextTest.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/SubscriptionsTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowContextsTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTesting.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowTesterTest.kt
tl;dr:
- `Workflow` -> `StatefulWorkflow`
- `Workflow` is an interface, `StatefulWorkflow` and `StatelessWorkflow` are abstract classes
that both implement `Workflow`.
This change makes it much easier for consumers of this library to define public APIs with private
implementations. The public API is an interface that extends `Workflow`. The private
implementation is a class that subclasses either `StatefulWorkflow` or `StatelessWorkflow`,
depending on whether it needs to keep track of any state. Either way, the workflow's state type
is kept as a completely private concern.
`interface Workflow<I, O, R>`
-----------------------------
This is the main currency of this library. `Workflow`s can compose
other `Workflow`s. A `Workflow` is anything that can be expressed as a `StatefulWorkflow`. …
=> Factor out a common parent interface for StatelessWorkflow and Workflow (now StatefulWorkflow).

kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/RealWorkflowContextTest.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/SubscriptionsTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowContextsTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowTesterTest.kt
This allows workflows to depend on their input to calculate their
state, even when being restored. It also reduces the entry points for
a workflow from two to one.
Closes #220.
=> Replace restoreState with a Snapshot param to initialState.

kotlin/build.gradle, kotlin/viewregistry-android/src/main/java/com/squareup/viewregistry/ModalContainer.kt, kotlin/viewregistry/build.gradle, kotlin/workflow-core/build.gradle, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-rx2/build.gradle, kotlin/workflow-testing/build.gradle
Also added configuration to generate dokka output for some modules.
=> Fixed broken kdoc links and some other warnings.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/RealWorkflowContext.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/CompositionIntegrationTest.kt
=> Add teardown hook on WorkflowContext.

kotlin/build.gradle, kotlin/samples/tictactoe/android/build.gradle, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/mainactivity/MainComponent.kt, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/HandlesBack.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalViewContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/PickledWorkflow.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowActivityRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowViewModel.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/ViewStateFrame.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/ViewStateStack.kt, kotlin/workflow-ui-android/src/main/res/values/ids.xml
One stop shopping to drive your activity from a workflow tree.
See the kdoc on [FragmentActivity.setContentWorkflow] in
[WorkflowActivityRunner.kt] for details.
This API is seriously locked down, suitable only for driving an entire
activity. We can open it up as other use cases emerge -- perhaps
a `WorkflowViewRunner` for embedding in legacy apps.
Closes #217
=> Introduces WorkflowActivityRunner.

kotlin/build.gradle
Closes #115.
This blocks the Gradle 5 bump (#275).
=> Upgrade Android Gradle Plugin to latest version.

swift/Tooling/Templates/Workflow (Verbose).xctemplate/___FILEBASENAME___Workflow.swift
A compose method can no longer return `Screen`, but must return a typed screen.
Updates the template to reflect this.
This means that the result of using the template will *not* compile until the screen returned from compose is one that is an actual type. However, I think it's a faster loop to finding this out than to have it be Screen and then be surprised by compiler errors later on.
Resolves #270
=> Updated compose in template to return an explicit Screen

kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealWorkflowContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealWorkflowContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/CompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt
=> Rename WorkflowContext.compose to composeChild.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealWorkflowContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealWorkflowContextTest.kt
=> Throw if WorkflowContext is accessed after compose returns.

kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealWorkflowContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/SubscriptionsTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowContextsTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/CompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowTesterTest.kt
=> Pass the workflow's scope into initialState.

kotlin/legacy/legacy-workflow-rx2/src/main/java/com/squareup/workflow/legacy/Screen.kt, kotlin/legacy/legacy-workflow-rx2/src/main/java/com/squareup/workflow/legacy/rx2/EventChannel.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealWorkflowContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealWorkflowContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/WorkflowContexts.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/SubscriptionsTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowContextsTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/CompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowTesterTest.kt
=> [kotlin] Rename compose and composeChild to render and renderChild.

kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/SubscriptionsTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowContextsTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTesting.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt
Commit cf3ae7bfa5f1d3778d057d5d200ee4126ba4cf58 accidentally stopped including
`baseContext` in the context for the workflow loop coroutine. This caused everything
not passing a dispatcher into `run` directly to default to the `Default` dispatcher,
which made a lot of things suddenly happen a lot lazier, and forced us to add a bunch
of additional calls in unit tests.
This PR adds `baseContext` back in, and also adds a default `CoroutineName` element
to aid in debugging.
=> Fix for WorkflowHost.Factory not using baseContext.

swift/Workflow/Sources/SubtreeManager.swift, swift/Workflow/Sources/WorkflowContext.swift, swift/Workflow/Tests/SubtreeManagerTests.swift
This immediately explodes (via `fatalError`) if a `WorkflowContext` is used after `render` returns.
This fixes #269
=> [#269] Invalidate WorkflowContext after `render` is called

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/LifetimeTracker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LifetimeTrackerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/CompositionIntegrationTest.kt
`SubtreeManager` is responsible for managing a `WorkflowNode`'s child `Workflow`s.
It uses `LifetimeTracker` to track children across render passes, start new ones,
and cancel old ones. It stores the `WorkflowOutputCase` as the `LifetimeTracker`'s
`Factory` type – "factories" have keys for deduping, and are used to create new
"disposables" when new ones are tracked. The `WorkflowOutputCase` also stores the
`handler` lambda that defines how to map a child workflow's output to a parent
`WorkflowAction`. This handler is re-created on every render pass (because it
closes over the workflow's state), and so the `LifetimeTracker` should always be
storing the most recent _instance_ of the `WorkflowOutputCase`. However, previously
it would only store the first factory for a given key. This meant …
=> Fix SubtreeManager not saving new case handlers.

kotlin/workflow-core/src/main/java/com/squareup/workflow/LifecycleWorker.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/LifecycleWorkerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
Don't have a use case for them being suspending, and making them suspending
might encourage more work to be done there than is appropriate.
Also improved docs.
=> Made LifecycleWorker methods non-suspending.

docs/concepts.md
=> Update Concepts doc to point out that workers can potentially send no events.

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowId.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
Making these types non-nullable doesn't add any inherent value or safety. There may be workflows
that want to define nullable types, so we should let them. Workflows that define their types to be non-nullable still get all the null safety they expect.
=> Remove non-nullable restriction from InputT, StateT, and RenderingT.

kotlin/build.gradle, kotlin/legacy/legacy-workflow-core/src/main/java/com/squareup/workflow/legacy/WorkflowOperators.kt, kotlin/legacy/legacy-workflow-core/src/test/java/com/squareup/workflow/legacy/CoroutineWorkflowTest.kt, kotlin/legacy/legacy-workflow-core/src/test/java/com/squareup/workflow/legacy/WorkflowOperatorsTest.kt, kotlin/legacy/legacy-workflow-rx2/src/main/java/com/squareup/workflow/legacy/rx2/EventChannel.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/WorkflowOperatorsTest.kt, kotlin/samples/tictactoe/android/build.gradle, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/RxWorkersTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowTesterTest.kt, kotlin/workflow-ui-android/build.gradle
Closes #188 because the deprecated `cancel` method that took `Throwable` has been removed.
The only real thing this "broke" was how legacy workflow's `switchMapState` handles channel cancellation,
now we have to be a bit more explicit. This is why channels shouldn't be used as streams…
=> Upgrade coroutines dependency to latest version.

kotlin/workflow-core/src/main/java/com/squareup/workflow/VeryExperimentalWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/FlowWorkersTest.kt
Closes #280.
I'm not actually sure this is something we should merge. I'm worried it might make people feel more comfortable using the Flow API than they should be, even though our integration is also tagged with experimental annotations. However, having it in the code base lets us track API and behavior changes and ensure our integration feels natural as the API stabilizes.
=> Add support for listening to Flow streams.

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-rx2-runtime/src/main/java/com/squareup/workflow/rx2/FlatMapWorkflow.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowActivityRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowViewModel.kt
Commit b5ed7b1517e7d234615b8b4a875ba6ab8e3fb3f0 removed the non-nullable upper bound on these types
in Workflow, but missed all the other places that had to duplicate that bound.
=> Remove the non-nullable Any upper bound on Input, State, and Rendering types in the rest of the code.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowId.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/MockChildWorkflow.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/MockWorker.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
Given a `StatefulWorkflow` or `StatelessWorkflow`, call `.testRender()` on it.
Pass the `InputT`, and for `StatefulWorkflow`s also pass the `StateT`.
This returns a `TestRenderResult` which provides access to the actual rendering
as well as methods to assert that children or workers were rendered and invoke
their output handlers.
=> Introduce alternative testing infrastructure to test single render passes more directly.

kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-rx2-runtime/src/test/java/com/squareup/workflow/rx2/FlatMapWorkflowTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/MockChildWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
Looking for feedback on whether this is actually nicer. This feels nice to me:
- "context" types are often receivers in these sort of helper builder higher-order functions.
- Don't need a separate override to make the input argument optional, since there's only one argument now.
=> Make the RenderContext parameter to Workflow.stateless the receiver instead.

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt
`RenderTester` currently requires all child workflows and workers that the workflow-under-test delegates to to be instances of `MockChildWorkflow` or `MockWorker`, respectively. This makes tests super verbose because if the actual type of a child workflow is a subinterface of `Workflow`, you need to actually implement that interface and can only use the mocks to do implementation-by-delegation, forcing you to repeat all the generics. It's extremely verbose. By removing this restriction, we can use mocking libraries to generate basic implementations of interfaces that should still work with the tester because all the assertion methods actually talk to the test context.
@rjrjr I want to land this in 0.16.1 as well, because I want to be able to use `RenderTester`.
=> Make RenderTester not require specific Mock* workflows/workers.

swift/Samples/SampleApp/Sources/DemoScreen.swift, swift/Samples/SampleApp/Sources/DemoWorkflow.swift, swift/Workflow/Sources/RenderContext.swift, swift/Workflow/Sources/SubtreeManager.swift, swift/Workflow/Sources/WorkflowHost.swift, swift/Workflow/Sources/WorkflowNode.swift, swift/Workflow/Tests/ConcurrencyTests.swift, swift/Workflow/Tests/SubtreeManagerTests.swift, swift/Workflow/Tests/WorkflowNodeTests.swift, swift/WorkflowTesting/Sources/WorkflowRenderTester.swift
This guarantees that an action being applied from a sink
will immediately cause a render pass, providing a new sink to
the UI side, and prevents lost events.
Additionally, fixes that the SignalProducer from a worker
was not being cancelled on a subsequent render pass if it
was not declared.
Fixes #348
=> Handle `Actions` from a sink synchronously.

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt
This allows customization of the ViewModel's dispatcher, since Dispatchers.Main isn't available on Buck builds.
=> Allow specifying the CoroutineDispatcher used by WorkflowRunnerViewModel

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt
In continuation of (https://github.com/square/workflow/pull/375),
since WorkflowViewModel is only exposed through WorkflowRunner,
allow specifying the CoroutineDispatcher in the WorkflowRunner,
so that the WorkflowViewModel can be started with a different dispatcher.
This allows Buck apps to use the WorkflowViewModel, since Kotlin's
Main Dispatcher is loaded via a ServiceLoader that isn't available
on Buck.
=> Allow specifying a different CoroutineDispatcher in the WorkflowRunner

kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt
Also added some additional kdoc on this method.
Prepares for #385, in which `onEvent` will return either a unique function or an always-equivalent function
depending on whether it's being used from a test or not.
=> Change RenderContext.onEvent return type to be a raw function type.

kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/BlinkingCursorWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
While the `@BuilderInference` annotation is still experimental, I am not worried about the
risk of using here because the worst thing that can happen is the wrong type is inferred
and the call site needs to specify an explicit generic type, which is already required
right now.
=> Use new builder inference for Worker.create so types can be inferred from emitOutput calls.

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/ViewStateCache.kt
Closes #400.
Our view persistence story got a lot simpler with the move to  `LayoutRunner`,
since we no longer try to render views before they have a complete rendering
to display. `BackStackContainer` didn't get the memo, and its assumption
that `onRestoreInstanceState` would come too late was breaking things.
Fix is simple, don't go like that.
=> Fixes BackStackContainer config change.

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/Named.kt
No longer necessary to save body state now that views are not created until
they have something to render. Use the recursive compatibility check from
`Named` when deciding whether or not to restore saved dialog state.
=> Cleans up persistence of ModalContainer.

README.md
The version number is taken from the published `workflow-core` artifact, but the link points to the page for all packages under the `com.squareup.workflow` group.
=> Added Maven Central and Apache License 2.0 badges to README

kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/HelloTerminalWorkflow.kt, kotlin/samples/hello-terminal/todo-terminal-app/src/main/java/com/squareup/sample/hellotodo/EditTextWorkflow.kt, kotlin/samples/hello-terminal/todo-terminal-app/src/main/java/com/squareup/sample/hellotodo/TodoWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
=> Rename WorkflowAction.noop() to noAction().

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/RxWorkersTest.kt
=> Add Completable.asWorker() operator.

kotlin/build.gradle, kotlin/legacy/legacy-workflow-core/src/main/java/com/squareup/workflow/legacy/CoroutineWorkflow.kt, kotlin/legacy/legacy-workflow-core/src/test/java/com/squareup/workflow/legacy/CoroutineWorkflowTest.kt, kotlin/legacy/legacy-workflow-core/src/test/java/com/squareup/workflow/legacy/ReactorAsWorkflowIntegrationTest.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt
- Some things that were `@FlowPreview` have been graduated to `@ExperimentalCoroutinesApi`.
- Breakage in `CoroutineWorkflow` was caused by https://github.com/Kotlin/kotlinx.coroutines/pull/1158.
- Breakage in `ReactorAsWorkflowIntegrationTest` was probably caused by https://github.com/Kotlin/kotlinx.coroutines/pull/1239.
=> Upgrade coroutines dep to 1.3.0-M1.

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/ViewStateCache.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/Compatible.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/Named.kt, kotlin/workflow-ui-core/src/test/java/com/squareup/workflow/ui/CompatibleTest.kt, kotlin/workflow-ui-core/src/test/java/com/squareup/workflow/ui/NamedTest.kt
`Compatibility.isCompatibleWith` could not easily be kept in sync with
`Named.key`, so now the latter is the only way to play the "same type but not
the same" game.
Closes #428.
=> Moves Named.key up to Compatible.compatibilityKey.

kotlin/build.gradle, kotlin/samples/hello-terminal/terminal-workflow/src/main/java/com/squareup/sample/helloterminal/terminalworkflow/TerminalWorkflowRunner.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/RealWorkflowHost.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealWorkflowHostTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
_There are two commits, the first just cleans up the existing `WorkflowHost` implementation to make the main change easier to implement and review._
The new Flows are backed by `BroadcastChannels`. The `renderingsAndSnapshots` Flow
is backed by a `ConflatedBroadcastChannel`, so it doesn't get backpressure and will
always emit the latest rendering + snapshot on collection. The `outputs` Flow is
a regular `BroadcastChannel` with a capacity of 1 (one more than the old channel,
which was unbuffered). `BroadcastChannel`s aren't allowed to be unbuffered, so while
this channel experiences backpressure, it's no longer perfect lock-step.
This change also updates all the internal consumers of `WorkflowHost`s to use the Flows.
Namely, `WorkflowTester` and `WorkflowRunnerViewModel`, the latter of …
=> Replace updates channel with rendering/snapshot and output Flows on WorkflowHost

kotlin/samples/hello-terminal/terminal-workflow/src/main/java/com/squareup/sample/helloterminal/terminalworkflow/TerminalWorkflowRunner.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt
Workflows accept _streams_ of inputs, which were previously passed around
as "channel producers" of the type `() -> ReceiveChannel<InputT>`.
Channels are not a good abstraction for this – they don't compose as well
as Flows, and they are inherently more expensive since they are meant to
be thread-safe, lock-free synchronization and queuing devices. Flows are
perfect for this API, since they are cold, easily composable, and map
directly to various reactive streams libraries (RxJava, Reactive Streams, etc.)
=> Convert InputT streams from channels to Flows.

kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/BlinkingCursorWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/LifecycleWorker.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/MockWorker.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkerTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/LifecycleWorkerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
The old `Worker` API was just an over-simplified copy of the `Flow` API.
Now that most core Flow APIs have graduated to "experimental" status, it
doesn't make sense to copy them. Using Flow directly has a few benefits:
- One less reactive streams contract to keep in your head (while the Worker
API was _similar_ to Flow, it was less strict and likely to diverge more
over time).
- We get access to all the built-in Flow operators.
- Out-of-the-box integration with various reactive streams libraries.
- Since Workers are always consumed as channels, we get lots of optimizations
when the source is also a channel, or knows how to make one. Flow
also does operator fusion for buffering and context-switching operators.
- The Kotlin Worker API now matches the Swift one almost exactly - the
only …
=> Convert the Worker API to use Flow instead of using its own Emitter type.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
When Workers were converted to flow in 045e5be2ebc2b65f83bc08e4a8e7959c7527f92e (#435), buffering
was introduced. `produceIn` will, by default, use the `BUFFERED` value to configure its channel's
capacity, which resolves to the "default" buffer size. This value is more than zero, which means
buffering was accidentally introduced into workers where it shouldn't be.
=> Fix Worker backpressure (too much buffering).

swift/Workflow/Sources/WorkflowAction.swift, swift/Workflow/Tests/SubtreeManagerTests.swift
Naming to match the same in Kotlin
Closes #425
=> Rename AnyWorkflowAction.identity to `noAction`

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
`runningWorker` is commonly used to run `Worker<Nothing>`s, as created
by `Worker.createSideEffect`. These workers typically do some work, then finish.
It makes no sense to throw an exception when they finish, that's expected behavior.
Fixes #455.
=> Don't throw from runningWorker when the worker finishes.

kotlin/build.gradle, kotlin/gradle.properties, kotlin/samples/hello-workflow-fragment/build.gradle, kotlin/samples/hello-workflow/build.gradle, kotlin/samples/tictactoe/android/build.gradle, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/mainactivity/MainComponent.kt, kotlin/samples/todo-android/todo-android-app/build.gradle, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/ViewStateCache.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/ViewStateFrame.kt
`androidx` deps are now grouped, and `versions` is now consistent: it only
holds shared values, others are inlined (as an increasing number already
were). Benefit, now the IDE nudges us when SDK gets stale.
=> Updates to sdk 29, and tidies dependencies.

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt
It's only used in this file, and we shouldn't pollute the auto-complete space for
`Context` and `Dialog` without really good reason.
=> Make lifecycleOrNull private.

kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
Also made the `Workflow.stateless` function inline.
This lets you define stateful workflows with a function call:
```kotlin
Workflow.stateful<Input, State, Output, Rendering>(
initialState = { input, snapshot -> TODO() },
render = { input, state -> renderChild(TODO()) },
snapshot = { state -> TODO() }
)
```
This is just an idea – does it really make anything better? These test workflows are a horrible test case for ergonomics because they're all very unusually short and usually only implement a subset of the functionality that a real workflow would implement.
=> Added builder functions for creating stateful workflows.

kotlin/build.gradle, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/authworkflow/LoginLayoutRunner.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/tictactoe/android/src/main/res/layout/login_layout.xml, kotlin/samples/tictactoe/android/src/main/res/values/strings.xml, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthState.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/LoginScreen.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt, kotlin/samples/todo-android/todo-android-app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/HandlesBack.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalViewContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/BackStackScreen.kt
Android's configuration changes make it very difficult to craft an API that
can catch all output values and also avoid double-processing of them, and each
such API we've come up with is very confusing. The cognitive cost  outweighs
the benefit of allowing the Activity or Fragment to consume a stream of
outputs — if that's even a benefit! So far we have no use cases for a stream
v. a single result code that can't be better handled inside the root workflow.
Note that we update the Tic Tac Toe sample to take advantage. We also
(nearly) make it's back button work properly on the initial screen, but
that is blocked by #466.
Closes #430.
=> WorkflowRunner now delivers single result instead of output stream.

Workflow.podspec, WorkflowTesting.podspec, WorkflowUI.podspec, kotlin/gradle.properties
Trying a slightly different approach to releasing this time - cutting a dedicated branch (`release-v0.18.0`) so we can continue to work on master.
=> Bump version number to 0.19.0.

kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt
`WorkflowAction.noAction()` can be highly utilized across consumers, and it's not depending on any particular input or output types. We can assume having the same object across invocations is safe, and it reduces the memory footprint.
=> Use single object for noAction instead of creating it on every call

kotlin/legacy/legacy-workflow-core/src/main/java/com/squareup/workflow/legacy/WorkflowPool.kt
Before, the renderings stream came from a regular `Channel`, and the replay/caching
happened downstream. In the legacy integration code, this meant that when a V2 workflow emitted
an output and got cancelled, the pool would immediately see the renderings channel was closed on the next
`onWorkflowUpdate` and emit `Finished`. Now that it's backed by a `ConflatedBroadcastChannel`, it will
always emit the last-emitted value on subscription before sending the close signal. This means the
pool will always see the last state, and emit `Running`, which means the v2 workflow just gets restarted
on the next iteration. Fixed by explicitly checking the `isActive` flag on the workflow's job before
emitting `Running`.
=> Fix WorkflowPool to work with ConflatedBroadcastChannel.

README.md
Forgot to update the name of the artifact used to retrieve our version badges, so they're still showing the old version.
=> Fix the maven version badges.

swift/Workflow/Sources/SubtreeManager.swift, swift/Workflow/Sources/WorkflowHost.swift, swift/Workflow/Tests/ConcurrencyTests.swift, swift/Workflow/Tests/WorkflowHostTests.swift
The UI receiving the screen or rendering from a workflow *should* synchronously update to use the newest sinks and closures on every render pass.
However, some declarative UI *may* not always update synchronously (for instance, will wait for the next render pass) which for very rapid UI originated events may result in an old sink being reused.
This change relaxes the strictness internally - as long as a subsequent render pass declares a sink of the same action type, it will be "reused" and thus proxy events from the prior sink through. If a sink of the same type is *not* declared, it will still be an error to send an action to a stale sink. This does not change the restriction for there only being a single action sent to a sink for each render pass.
Additionally, adds and `update` to …
=> [Swift] Allow reuse of sinks across render passes

.buildscript/build_swift_docs.sh, .gitignore, .travis.yml, RELEASING.md, deploy_website.sh, lint_docs.sh, mkdocs.yml
Old: Generate mkdocs site, then use Jazzy to dump heterogeneous HTML into the right spot.
New: Use [Sourcedocs]() to generate Markdown for swift APIs _before_ running mkdocs, then build the site like normal.
The Swift docs are now also built in CI to verify they build correctly.
Closes #508.
=> Embed the Swift API docs in the regular site.

kotlin/build.gradle, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
This is the first version of the library in which `receiveOrClosed` is available, but it's still internal. See #512.
Changelog: https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.0-rc
=> Upgrade coroutines to latest version (1.3.0-RC).

swift/WorkflowTesting/Sources/WorkflowRenderTester.swift
Plumbs the file and line to convenience render tester method.
This will cause errors to be reported at the calling site (in the test case) instead of within the library (was missed on the original addition)
=> Better errors for render tester convenience method

kotlin/gradle/wrapper/gradle-wrapper.properties
Release notes: https://docs.gradle.org/5.6/release-notes.html
=> Upgrade Gradle to latest version (5.6).

kotlin/workflow-core/src/main/java/com/squareup/workflow/LifecycleWorker.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/LifecycleWorkerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
Added notes in the kdoc about the order in which these methods are called.
Closes #503.
@pyricau Tried to address your documentation feedback, PTAL.
=> Rename LifecycleWorker.onCancelled to onStopped.

kotlin/build.gradle, kotlin/legacy/legacy-workflow-core/build.gradle, kotlin/legacy/legacy-workflow-core/src/main/java/com/squareup/workflow/legacy/Reactor.kt, kotlin/legacy/legacy-workflow-rx2/build.gradle, kotlin/legacy/legacy-workflow-rx2/src/main/java/com/squareup/workflow/legacy/rx2/Reactor.kt, kotlin/samples/dungeon/app/build.gradle, kotlin/samples/dungeon/common/build.gradle, kotlin/samples/tictactoe/app/build.gradle, kotlin/samples/tictactoe/common/build.gradle, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameState.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainState.kt, kotlin/samples/todo-android/app/build.gradle, kotlin/samples/todo-android/common/build.gradle, kotlin/workflow-core/build.gradle, kotlin/workflow-runtime/build.gradle, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowId.kt, kotlin/workflow-rx2/build.gradle, kotlin/workflow-testing/build.gradle, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/HandlesBack.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt, kotlin/workflow-ui-core/build.gradle, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/Named.kt
Kotlin Reflect is a heavy dependency and the modules barely make use of it to justify the
dependency.
=> Remove all direct dependencies on Kotlin Reflect. 

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkerSink.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkerSinkTest.kt
=> Introduce WorkerSink for writing integration tests that involve worker outputs.

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt
Closes #558, removes 1/2 of #512 TODOs, and closes #434.
=> Remove runningWorkerUntilFinished.

swift/WorkflowTesting/Sources/RenderExpectations.swift, swift/WorkflowTesting/Sources/WorkflowRenderTester.swift, swift/WorkflowTesting/Tests/WorkflowRenderTesterTests.swift
While the child output was specified, it wasn't being applied when
simulating a render pass.
Fixes #592
=> [Swift] Apply child workflow output as an action in RenderTester

kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/AiWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
Cleaned up some obsolete documentation in that file too.
Follow-up to #606 (6ed4208a02f9e6f3788b106375195df273d04e3d).
Closes #605 (again).
=> Remove some extra key parameters that snuck through the first cleanup.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
It still had the `#performWork` example which needed to change to `#run`. I'm also using this as a chance to use the much easier coroutine syntax.
=> Update the Worker "Network request" example

kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
Two commits, I'd recommend reviewing individually.
Fixes #506
=> Never pass an empty snapshot to initialState.

Package.swift, Workflow.podspec, WorkflowTesting.podspec, docs/tutorial/adding-workflow-to-a-project.md, docs/tutorial/building-a-workflow.md, docs/tutorial/using-a-workflow-for-ui.md, swift/Samples/SampleApp/Sources/DemoWorkflow.swift, swift/Tooling/Templates/Workflow (Verbose).xctemplate/___FILEBASENAME___Workflow.swift, swift/Workflow/Sources/RenderContext.swift, swift/Workflow/Sources/SubtreeManager.swift, swift/Workflow/Sources/Worker.swift, swift/Workflow/Sources/WorkflowHost.swift, swift/Workflow/Tests/AnyWorkflowTests.swift, swift/Workflow/Tests/ConcurrencyTests.swift, swift/Workflow/Tests/SubtreeManagerTests.swift, swift/Workflow/Tests/WorkflowNodeTests.swift, swift/WorkflowTesting/Sources/WorkflowRenderTester.swift, swift/WorkflowTesting/Tests/WorkflowRenderTesterTests.swift, swift/WorkflowUI/Sources/Container/ContainerViewController.swift, swift/WorkflowUI/Tests/ContainerViewControllerTests.swift
Updating ReactiveSwift to 6.0.0
- Remove the dependency on `antitypical/Result` in favor of Swift 5's `Swift.Result`
- Replace `NoError` with `Swift.Never` since `Never` now conforms to `Swift.Error` [Swift Evolution Proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0215-conform-never-to-hashable-and-equatable.md)
=> Update ReactiveSwift to 6.0.0

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt
I think this fixes #626.
Likely caused by https://github.com/Kotlin/kotlinx.coroutines/issues/1584.
cc @SalvatoreT
=> Stop using onReceiveOrClosed because it is extremely broken.

.travis.yml, kotlin/.idea/misc.xml, kotlin/benchmarks/src/jmh/java/com/squareup/workflow/benchmarks/DeepRenderBenchmark.kt, kotlin/build.gradle
The benchmarks won't actually run in CI, since CI is too unpredictable performance-wise
to generate consistent and meaningful data, and they are slow to run. But this should
prevent us from breaking them again in the future.
This also adds the `.idea/misc.xml` file to git, so we can persist the suppression of warnings about benchmarks not being used anywhere.
=> Fix benchmarks compilation errors, update gradle plugin version, and build in CI.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
This makes it easier to use when you don't actually care about the return type,
and serves as documentation that the worker never emits.
=> Change the return type of Worker.finished from T to Nothing.

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkerTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
I think this was causing some test flakes, so this should fix #591.
Also removed the context parameter to `Worker.test`, since it was only there
to use with `TestCoroutineContext` but that apparently doesn't support `yield`
so it's no longer necessary.
=> Remove racy hack in WorkerTester.

README.md
It doesn't render correctly in github, but Mkdocs handles it fine.
=> Embed the Droidcon NYC '19 video in the README.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorker.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/RxWorkerTest.kt
As I was upgrading us to 0.21.0 internally, realized that some code needing custom workers was calling `asFlow()`, which requires an experimental annotation. This is just to avoid that.
=> Add an RxWorker class so Workers can be implemented without using experimental Flow APIs.

kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/PublisherWorker.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/PublisherWorkerTest.kt
`Publisher` is the non-rx-specific interface from the `reactive-streams` library
that `Flowable` implements, and that all the `Flow` extensions for `Flowable`
are actually defined on.
=> Make RxWorker and Flowable.asWorker use Publisher instead of Flowable.

.travis.yml, swift/Samples/Tutorial/Frameworks/Tutorial1Complete/Sources/Welcome/WelcomeWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Todo/List/TodoListWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Welcome/WelcomeWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/Edit/TodoEditWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/List/TodoListWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Welcome/WelcomeWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/Edit/TodoEditWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/List/TodoListWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/TodoWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Welcome/WelcomeWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/Edit/TodoEditWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/List/TodoListWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/TodoWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Welcome/WelcomeWorkflow.swift, swift/Samples/Tutorial/Tutorial3.md, swift/Samples/Tutorial/Tutorial4.md
Fixes #655 
* Remove all the `import Result`s from the tutorials and tutorial code
* Use `Never` instead of `NoError`
=> Update tutorials for Swift 5/ReactiveSwift 6.0

kotlin/samples/tictactoe/app/src/androidTest/java/com/squareup/sample/TicTacToeEspressoTest.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/BuilderBinding.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/LayoutRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewShowRendering.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowViewStub.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/ViewStateCache.kt
The rendering in a view's `ViewShowRendering` tag is now updated on each call
to `View.showRendering`. Access to that value and the `showRendering` function
itself is improved with new `View.getRendering` and `View.getShowRendering`
methods. With their introduction, we're able to make `View.showRenderingTag`
private.
Also updates `WorkflowLayout` to use `WorkflowStubView`. It's pretty thrilling
that this didn't break the view persistence code. Wasn't able to pull off the
same trick for BackStackContainer or ModalContainer, so the more fundamental
`ViewRegistry` and `ViewShowRendering.kt` methods are staying public. Punched
up their documentation. (Had to go with `fun` rather than `val` on the new
code due to all the param types.)
Another point for discussion: thought about changing …
=> Adds getRendering, getShowRendering.

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
=> Make onEvent, makeActionSink, and makeEventSink include what action was lost to when they receive more than one event.

kotlin/build.gradle
Makes #675 obsolete (closes #675).
=> Remove robolectric dependency definition, we're never actually using it.

kotlin/build.gradle, kotlin/samples/dungeon/app/build.gradle, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/MainActivity.kt, kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/BlinkingCursorWorkflow.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt, kotlin/samples/tictactoe/app/build.gradle, kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/todo-android/app/build.gradle, kotlin/samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
We now use `androidx.savedstate` for persistence purposes, so the
`WorkflowRunner` Android integration API is as simple as it  will ever be.
Closes #431.
=> Eliminates WorkflowRunner.onSaveInstanceState.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Snapshot.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/TreeSnapshotsTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
This PR gives you the option of starting a workflow test session with either just the snapshot for the root workflow itself, or the complete snapshot of the entire tree from a previous workflow run.
Fixes #538.
=> Make it possible to pass just the snapshot for the root workflow into the test methods.

.travis.yml, Package.swift, swift/Workflow/Sources/SubtreeManager.swift, swift/WorkflowUI/Sources/Screen/AnyScreen/AnyScreenViewController.swift
Now that Xcode 11 supports Swift Package Manager directly, tests can be executed from the command line with `xcodebuild`. This allows us to specify an SDK (including iOS) and simulator device, which unlocks testing of code with system (UIKit/SwiftUI/AppKit) dependencies directly from the Swift package – no CocoaPods required.
=> Add WorkflowUI to Package.swift

kotlin/samples/tictactoe/app/src/androidTest/java/com/squareup/sample/TicTacToeEspressoTest.kt, kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/tictactoe/app/src/main/res/layout/login_layout.xml, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/MasterDetailContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/BackStackAware.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/BackStackScreen.kt, kotlin/workflow-ui-core/src/test/java/com/squareup/workflow/ui/BackStackScreenTest.kt
Previously we only enforced this with a runtime check.
Inspired by #676.
=> Compile time assurance that BackStackScreen is not empty.

swift/WorkflowUI/Sources/Screen/AnyScreen/AnyScreenViewController.swift
I found this while adding Swift Package Manager support for WorkflowUI; it seems as though `UIKit` is magically imported when building with Cocoapods in Xcode.
(stay tuned for actual SPM support, it's a bit more complicated)
=> Add missing UIKit import

kotlin/internal-testing-utils/build.gradle, kotlin/internal-testing-utils/gradle.properties
Because the `internal-testing-utils` module wasn't configured to publish to maven, the modules that depend on it were using version `unspecified` in their POMs. This was invalid, but also the shared artifact just wasn't being published, so everything breaks consumers.
=> Publish internal testing artifact, required by other published artifacts.

RELEASING.md
Sourcedocs doesn't seem to support Xcode 11, see https://github.com/eneko/SourceDocs/issues/30
=> Add note in RELEASING about only using Xcode 10.

README.md
Swift Package Manager makes getting started with Workflow dramatically easier for anyone who is not already running Cocoapods, so we should advertise its support in the readme (This should have been in my initial SPM PR).
=> Add SPM instructions to README

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
Fixes #714.
(cherry picked from commit fc37ebab53acd4d9316472c1e0cd615395ad9c06, accidentally merged the original PR into master instead of release-v0.21.0)
=> [cherrypick] Restore `testFromState`.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
Fixes #741, based on #743.
This change is actually very simple, it just replaces the per-render-pass `CompletableDeferred` with a per-`WorkflowNode`, unlimited-capacity `Channel`.
=> Make event sinks queued and reusable instead of throw after going stale.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-core/src/test/java/com/squareup/workflow/WorkerTest.kt
=> Give Worker.doesSameWorkAs a default implementation that just compares by concrete type.

swift/WorkflowUI/Sources/Container/ContainerView.swift, swift/WorkflowUI/Sources/Container/WorkflowView.swift
This change allows a workflow to be used directly within a SwiftUI hierarchy. Note that `ViewRegistry` is no longer in play as SwiftUI views are already simple value types.
There are two ways to use `ContainerView`:
You can provide a `content` closure to `init(workflow:onOutput:content:)` to map the workflow's rendering into a SwiftUI view hierarchy:
```swift
var body: some View {
ContainerView(workflow: MyWorkflow(), onOutput: self.handleOutput) { rendering in
VStack {
Text("The value is \(rendering.value)")
Button(action: rendering.onIncrement) {
Text("+")
}
Button(action: rendering.onDecrement) {
Text("-")
}
}
}
}
```
Or, if the rendering type already conforms to `View`, you can omit the closure:
```swift
var body: some View {
ContainerView(workflow: MyWorkflow(), onOutput: …
```
=> Add ContainerView to enable SwiftUI integration

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
=> Fix RenderTester not allowing output-less expectations to be specified after one with output.

.travis.yml
This allows the UI tests to fail/error independently, and hopefully allows the
tests to start without waiting for lint checks.
Hopefully makes issues like #759 easier to spot and workaround temporarily in the future.
=> Split the Android instrumentation tests into their own Travis shard.

kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/masterdetail/MasterDetailContainer.kt, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/BoardView.kt, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/GameLayoutRunner.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/BaseScreenLayoutRunner.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/ChooseRowTypeViewBinding.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/AlertContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/BuilderBinding.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ContainerHints.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/LayoutRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalViewContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewBinding.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowViewStub.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/ContainerHintsTest.kt
`LayoutRunner` constructors and `bindView` factory methods no longer have the
option to include a `ViewRegistry` parameter. Instead, every `ContainerHint`
map includes a hint pointing to the related `ViewRegistry`.
This further simplifies the chore of creating custom container views.
They no longer have to build a mechanism for getting their hands
on a `ViewRegistry` reference. In this PR you'll see various
`registry = viewRegistry` lines deleted from various factory functions
in various `BuilderBinding` calls, e.g. in `AlertContainer`,
`ModalViewContainer` and `BackStackContainer`.
Closes #737.
=> BREAKING CHANGE: ViewRegistry is now a ContainerHint.

kotlin/build.gradle
Closes #765 and closes #766.
Bumps [moshi](https://github.com/square/moshi) from 1.9.1 to 1.9.2.
- [Release notes](https://github.com/square/moshi/releases)
- [Changelog](https://github.com/square/moshi/blob/master/CHANGELOG.md)
- [Commits](https://github.com/square/moshi/compare/moshi-parent-1.9.1...moshi-parent-1.9.2)
Bumps [moshi-kotlin](https://github.com/square/moshi) from 1.9.1 to 1.9.2.
- [Release notes](https://github.com/square/moshi/releases)
- [Changelog](https://github.com/square/moshi/blob/master/CHANGELOG.md)
- [Commits](https://github.com/square/moshi/compare/moshi-parent-1.9.1...moshi-parent-1.9.2)
Verified UI tests pass locally.
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
=> Bump moshi and moshi-kotlin from 1.9.1 to 1.9.2 in /kotlin

.travis.yml, Package.swift, Workflow.podspec, WorkflowTesting.podspec, WorkflowUI.podspec, swift/WorkflowUI/Sources/Container/ContainerViewController.swift, swift/WorkflowUI/Sources/Container/WorkflowView.swift, swift/WorkflowUI/Sources/Screen/AnyScreen/AnyScreen.swift, swift/WorkflowUI/Sources/Screen/AnyScreen/AnyScreenViewController.swift, swift/WorkflowUI/Sources/Screen/AnyScreen/UntypedScreenViewController.swift, swift/WorkflowUI/Sources/Screen/ScreenViewController.swift, swift/WorkflowUI/Sources/ViewRegistry/ViewRegistry.swift, swift/WorkflowUI/Tests/AnyScreenViewControllerTests.swift, swift/WorkflowUI/Tests/ContainerViewControllerTests.swift, swift/WorkflowUI/Tests/ViewRegistryTests.swift
For now this primarily marks `UIKit` code as unavailable when not compiling for iOS. The benefit today is that we can run unit tests directly on macOS.
As we add SwiftUI support in the future, a common API across Apple platforms becomes more interesting (which was the real motivation behind this PR).
=> Add macOS support

kotlin/gradle/wrapper/gradle-wrapper.properties
Gradle 6.0 release notes: https://docs.gradle.org/6.0/release-notes.html
Gradle 6.0.1 release notes: https://docs.gradle.org/6.0.1/release-notes.html
This depends on upgrading ktlint first (#780), the version we're currently using doesn't work with Gradle 6.
=> Upgrade Gradle to 6.0.1.

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
This fix will prevent sends from the workflow's _own_ render method is called,
but not the more general case of the entire tree's render pass being complete.
The reason for this is that this is just a safety check to provide a more useful
error message than a raw stack overflow, and uses the existing `frozen` flag
private to the current node, so doesn't add any machinery to the overall tree.
Fixes #764.
=> Prevent sending to sinks before the workflow's own render method returns.

kotlin/build.gradle, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/CoroutineEventChannelTest.kt, kotlin/samples/dungeon/timemachine-shakeable/src/main/java/com/squareup/sample/timemachine/shakeable/ShakeWorker.kt, kotlin/trace-encoder/src/main/java/com/squareup/tracing/TraceEncoder.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/PublisherWorker.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/PublisherWorkerTest.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt
Also removes some experimental annotations that are no longer necessary, and makes others more targeted so it's more obvious when they can be removed in the future.
=> Upgrade coroutines to 1.3.3

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
- Give RenderTester.render function argument a default no-op value. Fixes #814.
- Add overload to RenderTester.expectWorker for simple worker comparisons.
- Improve documentation on state-less renderTester.
=> Improve renderTester API

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/InlineLinkedList.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowChildNode.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/InlineLinkedListTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt
This optimization moves the management of child workflows out
of `Behavior` and `LifetimeTracker` and directly into `SubtreeManager`.
It uses roughly the same algorithm as the Swift implementation (I believe),
and during a render pass just effectively tags nodes as still in-use or not,
by moving them between two linked lists. After the render pass, everything that
is in the old list is torn down and the lists are swapped for the next render pass.
This reduces the number of allocations required by each `WorkflowNode`'s `render`,
and in the optimal case of a workflow just re-rendering all its children, has
almost no overhead.
[Spreadsheet](https://docs.google.com/spreadsheets/d/1e4OBW0RmKscQyQPIYMLHf0Tzj2WbBnOndVLnEcJ5MAg/edit?usp=sharing)
Benchmark | (treeShape) | Mode | Cnt | Score …
=> Optimize re-rendering child workflows.

kotlin/samples/containers/app-poetry/src/main/java/com/squareup/sample/poetryapp/PoetryActivity.kt, kotlin/samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt, kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/BindingViewRegistry.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/CompositeViewRegistry.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/NamedBinding.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/BindingViewRegistryTest.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/CompositeViewRegistryTest.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/TestBinding.kt
=> Convert ViewRegistry to an interface.

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Sink.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt
`WorkflowAction`'s output type is, as the name suggests, an output value,
and so it is natural that it have `out` variance (i.e. be covariant). This was changed because
the new `Updater` API stores the pending output value in a var, which is readable
as well as writeable and therefore an invariant (`in`) position, and therefore `Updater`'s `O`
must be neither `in` nor `out` (i.e. be invariant), and `WorkflowAction`'s `OutputT` must, in turn, also be invariant.
However, the only _API_ in which `Updater` exposes this type is as a method parameter,
which is an `in` position. It is only _read_ in the same context as the `WorkflowAction` for which
it was created, which means its type will never actually be out of bounds. Therefore, we can
just mark the output use of `Updater.O` as …
=> Make WorkflowAction covariant on OutputT again.

kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/PoemWorkflow.kt, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt, kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/PlayerWorkflow.kt, kotlin/samples/dungeon/timemachine-shakeable/src/main/java/com/squareup/sample/timemachine/shakeable/ShakeableTimeMachineWorkflow.kt, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/AppWorkflow.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/editablelistworkflow/EditableListWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoEditorWorkflow.kt, kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
It looks weird to say `context.send`, and weirder to say `context.contraMap` –
what does it mean to "contra map" a `RenderContext`? It makes more sense to say
a context _has_ a sink than it _is_ a sink. Only slightly more typing but much
more clear.
=> Undo making RenderContext a sink, give it a sink property instead.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/NullFlowWorker.java, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
Per #842:
> In unit tests, if you use Mockito to create a Worker, the `run` method will return `null` even though the return type is non-nullable in Kotlin. Kotlin helps out with this by throwing an NPE before control is returned to any kotlin code, but the NPE that it throws includes an almost completely useless stacktrace and no other details.
>
> We can do better: When calling `worker.run()`, we can catch the NPE and throw a wrapper exception that asks if you're using mocks and reminds you to do the right thing.
Closes #842
=> #842: Detect possible Worker mock setup issues.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
Also fills out the worker docs some more.
Closes #848.
=> Give worker coroutines descriptive names for debugging.

kotlin/samples/hello-terminal/todo-terminal-app/src/main/java/com/squareup/sample/hellotodo/TodoWorkflow.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt, kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowDiagnosticListener.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowDiagnosticListenerIntegrationTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/PublisherWorkerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
`v0.22.0` changed `Workflow.invoke()` to use `Updater` instead of `Mutator`.
That's a breaking change, but it compiles just fine  -- updating to `v0.22.0`
or later is a fraught process.
Motivated by that, this change eliminates `WorkflowAction.invoke` entirely,
replacing it with an `action` function that parallels `StatefulWorkflow.action`
and `StatelessWorkflow.action`.
However we got here, I'm pretty happy with the final shape!
=> WorkflowAction.invoke is now action

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
From the kdoc:
> The dispatcher is always set to `Unconfined` to
>    *   minimize overhead for workers that don't care which thread they're executed on (e.g. logging
>    *   side effects, workers that wrap third-party reactive libraries, etc.). If your work cares
>    *   which thread it runs on, use `withContext` or
>    *   `flowOn` to specify a dispatcher.
Previously, the workers would run on the same dispatcher as the workflow runtime (`Main.immediate`), which meant that if the worker was wrapping, e.g., an `Observable` that was emitting on a background thread, the coroutine would dispatch back onto the main thread before sending to the channel, which is completely unnecessary, since channels are already thread-safe.
This doesn't change the threading behavior for simple …
=> Make all workers run on the Unconfined dispatcher.

Workflow.podspec, WorkflowTesting.podspec, WorkflowUI.podspec, kotlin/gradle.properties, kotlin/samples/tictactoe/app/src/androidTest/java/com/squareup/sample/TicTacToeEspressoTest.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewShowRendering.kt
We're already storing the most recent rendering in view tags. It's weird that we don't do so for the ContainerHints that are always provided at render time, and the lack is actually getting in my way as I build custom containers.
(Note additional commit to bump the version number.)
=> Adds ContainerHints to ShowRenderingTag.

swift/WorkflowTesting/Sources/WorkflowActionTester.swift, swift/WorkflowTesting/Sources/WorkflowRenderTester.swift
**Issue:**
`pod trunk push WorkflowTesting.podspec` fails during validation.
**Reason:**
`Workflow` is built with `ENABLE_TESTABILITY=NO` for `Release` builds, causing `@testable import WorkflowTesting` to fail compilation in `Release`. 
**Proposal:**
`WorkflowTesting` is meant to be used for Unit Testing only. Flag out the relevant bits when not in `Debug` mode.
=> Flag out WorkflowTesting APIs when in Release mode

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt
=> Allow empty snapshots to be passed into launchWorkflowIn.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
It was initially like this, and then I switched it to `Nothing` to make the function simpler,
but I just realized that most of the uses do a cast anyway so it's better to just have a more
generic type. This is also more consistent with `emptyList()`, `emptyFlow()`, etc.
cc @ellapolo
=> Paramaterize the return type of Worker.finished() to make it more convenient to use in tests.

kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/panel/PanelContainer.kt, kotlin/samples/containers/android/src/main/res/anim-sw600dp/panel_enter.xml, kotlin/samples/containers/android/src/main/res/anim-sw600dp/panel_exit.xml, kotlin/samples/containers/android/src/main/res/anim/panel_enter.xml, kotlin/samples/containers/android/src/main/res/anim/panel_exit.xml, kotlin/samples/containers/android/src/main/res/values/styles.xml, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt
@zach-klippenstein demonstrates that dialog based modals can work just fine with tab / IME navigation, and with very simple code. And fixes mismatched speed on default `BackStackContainer` transition.
=> Improved animation for BackStackContainer, PanelContainer.

kotlin/.buildscript/configure-dokka.gradle, kotlin/build.gradle, kotlin/workflow-ui-android/build.gradle
Closes #651.
This technically fixes #569 as well (according to https://github.com/vanniktech/gradle-maven-publish-plugin/issues/54),
and after uploading the artifact server has the sources jar with the actual sources inside. However, when
consuming via gradle, IntelliJ still isn't showing the sources for AARs (it is for JARs). The android artifacts
have a `-api` suffix however, so I'm wondering if the source jars are getting lost in some transformation
(maybe Jetifier?).
Note that the javadocs jars are on the server but they're all empty (for android and non-android
artifacts), but IntelliJ seems to be just fine pulling the kdoc from the source jars, so I guess the source jars
are all that is required for documentation.
=> Upgrade Dokka to 0.10.0 and maven publish to 0.9.0-SNAPSHOT.

kotlin/gradle.properties
I don't think we're using any libraries any more that use the support library,
so we don't need to waste build time jetifying everything.
=> Disable Jetifier.

kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-core/src/test/java/com/squareup/workflow/WorkerTest.kt, kotlin/workflow-tracing/src/test/resources/com/squareup/workflow/diagnostic/tracing/expected_trace_file.txt
This change allows `TypedWorker`s to be distinguished by type parameters
on their type parameters (e.g. `Worker<List<String>>` vs `Worker<List<Int>>`),
instead of just the erased type (e.g. `Worker<List>` vs `Worker<List>`).
=> Use KType instead of KClass in TypedWorker.

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTestResult.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
=> Make verifyAction and verifyActionResult support no processed action.

kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/SampleContainers.kt, kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/panel/Contexts.kt, kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/panel/PanelContainer.kt, kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/panel/ScrimContainer.kt, kotlin/samples/containers/android/src/main/res/anim-sw600dp/panel_enter.xml, kotlin/samples/containers/android/src/main/res/anim/panel_enter.xml, kotlin/samples/containers/android/src/main/res/values-land/bools.xml, kotlin/samples/containers/android/src/main/res/values/bools.xml, kotlin/samples/containers/android/src/main/res/values/colors.xml, kotlin/samples/containers/android/src/main/res/values/styles.xml, kotlin/samples/containers/common/src/main/java/com/squareup/sample/container/panel/PanelContainerScreen.kt, kotlin/samples/containers/common/src/main/java/com/squareup/sample/container/panel/ScrimContainerScreen.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/AppWorkflow.kt, kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/tictactoe/app/src/main/res/layout/second_factor_layout.xml, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/AlertContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalViewContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/AlertContainerScreen.kt, kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/HasModals.kt
Trying to protect container authors from calling the `Dialog`
constructor was foolish. Didn't actually simplify anything,
and made it very difficult to manage window size.
Panel sample behavior around soft keyboard is a lot better now.
=> Drastically simplifies ModalViewContainer.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
This doesn't change any behavior, it is just more efficient: there's no need to
define the function at the tick pass, so this is not only more efficient but also
just easier to read, since there are fewer moving parts.
This is also required for #910.
=> Pass acceptOutput function to WorkflowNode constructor instead of every tick pass.

kotlin/build.gradle
`activity-ktx` includes [only two helper classes ](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/activity/activity-ktx/src/main/java/androidx/activity) which are not used by workflow. If someone needs this functionality, they can add extensions manually.
`activity`, on the other hand is used - it contains `OnBackPressedDispatcher` & friends.
=> Replaced activity-ktx dependency with activity. 

README.md
Merging this into the release branch since that's where this changed and docs published from this branch should reflect that, but not publishing a new maven/cocoapods release.
Fixes #934.
=> Update README to document new Android UI artifacts.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LaunchWorkflowTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
This is helpful for tests that need to be able to control time.
This functionality was covered by the test's dispatcher, but since #851 changed the dispatcher used for workers, we need to be able to configure workers' contexts separately.
=> Make the context used to start workers configurable for tests.

CHANGELOG.md, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LaunchWorkflowTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
This is an enhancement to #940 that gives more reasonable behavior. The context
parameter to the test methods are primarily used to pass in test dispatchers, and
those dispatchers often really only need to be used for workers.
Since I don't know of a use case for specifying context separately just for workers,
this also removes the `WorkflowTestParams.workerContext` property.
=> Make WorkflowTester tests use the main context as the worker context.

kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/BindingViewRegistry.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/CompositeViewRegistry.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui/core-android/src/test/java/com/squareup/workflow/ui/CompositeViewRegistryTest.kt
The lack of typing caused a bug integrating with some legacy code, and wasn't
needed or useful, so fixing the type.
=> Make ViewRegistry's key set strictly-typed to KClass<*> instead of Any.

kotlin/.buildscript/binary-validation.gradle, kotlin/build.gradle, kotlin/internal-testing-utils/api/internal-testing-utils.api, kotlin/legacy/legacy-workflow-core/api/legacy-workflow-core.api, kotlin/legacy/legacy-workflow-rx2/api/legacy-workflow-rx2.api, kotlin/legacy/legacy-workflow-test/api/legacy-workflow-test.api, kotlin/trace-encoder/api/trace-encoder.api, kotlin/workflow-core/api/workflow-core.api, kotlin/workflow-runtime/api/workflow-runtime.api, kotlin/workflow-rx2/api/workflow-rx2.api, kotlin/workflow-testing/api/workflow-testing.api, kotlin/workflow-tracing/api/workflow-tracing.api, kotlin/workflow-ui/backstack-common/api/backstack-common.api, kotlin/workflow-ui/core-common/api/core-common.api, kotlin/workflow-ui/modal-common/api/modal-common.api
Ignores all leaf sample projects individually, wildcards are not supported (see https://github.com/Kotlin/binary-compatibility-validator/issues/3).
Closes #243.
=> Add JetBrain's new kotlin binary compatibility validator to start tracking changes to our ABI.

CHANGELOG.md, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
PRs #940 and #943 have a bug where the worker context isn't passed from a parent workflow
to child `WorkflowNode`s. This fixes that.
=> Plumb workerContext to child workflows.

.gen_config.yml, Gemfile, Gemfile.lock
This will provide the following improvements to the development workflow:
1. `bundle exec pod gen` can be run with no arguments, and `Development.podspec` will automatically be selected.
2. Sample apps will now include their respective unit tests in their scheme, so `CMD-U` can be used to run tests in Xcode for each sample app
3. Config variables can now be used in scheme environment variables (ex. `$(SRCROOT)`)
=> Update CocoaPods, cocoapods-generate, and Xcodeproj

CHANGELOG.md, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
The worker type should be unbounded, _not_ the same as the _Workflow's_ output type.
=> Fix type parameter for expectWorker accepting Worker instance.

kotlin/.buildscript/binary-validation.gradle, kotlin/build.gradle, kotlin/legacy/legacy-workflow-core/api/legacy-workflow-core.api, kotlin/legacy/legacy-workflow-rx2/api/legacy-workflow-rx2.api, kotlin/workflow-core/api/workflow-core.api, kotlin/workflow-rx2/api/workflow-rx2.api, kotlin/workflow-testing/api/workflow-testing.api, kotlin/workflow-ui/backstack-android/api/backstack-android.api, kotlin/workflow-ui/core-android/api/core-android.api, kotlin/workflow-ui/core-compose/api/core-compose.api, kotlin/workflow-ui/modal-android/api/modal-android.api
[Here's the release notes](https://github.com/Kotlin/binary-compatibility-validator/releases/tag/0.2.0) (interesting changes are all in 0.2.0, but latest version is actually 0.2.1).
Highlights:
- Android support!
- `inline reified` functions are no longer considered as public ABI
The plugin configuration now automatically ignores any projects in the `samples` directory,
instead of listing them explicitly.
=> Update binary-compatibility-validator plugin to 0.2.1.

docs/tutorial/building-a-view-controller-from-screen.md, docs/tutorial/using-a-workflow-for-ui.md, swift/Samples/Tutorial/Tutorial1.md, swift/Samples/Tutorial/Tutorial2.md, swift/Samples/Tutorial/Tutorial3.md, swift/Tooling/Templates/Screen (View Controller).xctemplate/___FILEBASENAME___Screen.swift
An initial pass to remove all mentions of `ViewRegistry`. We will be doing another pass to document `ViewControllerDescription` with additional examples. That's tracked in #991
=> Update docs to reflect ViewRegistry removal:

kotlin/build.gradle
Missed this in the original 1.3.70 PR, #993.
=> Fix build.gradle to use renamed compiler flag -Xopt-in

kotlin/.buildscript/android-ui-tests.gradle, kotlin/samples/containers/app-poetry/build.gradle, kotlin/samples/containers/app-raven/build.gradle, kotlin/samples/containers/hello-back-button/build.gradle, kotlin/samples/dungeon/app/build.gradle, kotlin/samples/hello-compose-binding/build.gradle, kotlin/samples/hello-workflow-fragment/build.gradle, kotlin/samples/hello-workflow/build.gradle, kotlin/samples/recyclerview/build.gradle, kotlin/samples/tictactoe/app/build.gradle, kotlin/samples/todo-android/app/build.gradle
2 commits:
1. Factor out Android UI test gradle config into a separate file.
2. Enable AndroidX test orchestrator to try to reduce flakiness.
Note this was originally attempted in #912, but we never got it working.
=> Enable AndroidX test orchestrator to try to reduce flakiness.

kotlin/build.gradle, kotlin/gradle.properties, kotlin/samples/hello-workflow/build.gradle, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloViewFactory.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt, kotlin/samples/hello-workflow/src/main/res/layout/hello_goodbye_layout.xml, kotlin/workflow-ui/backstack-android/api/backstack-android.api, kotlin/workflow-ui/core-android/api/core-android.api, kotlin/workflow-ui/core-android/build.gradle, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/LayoutRunner.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/ViewBindingViewFactory.kt
Initially proposed by @0legg.
Closes #984.
```kotlin
val HelloBinding: ViewBinding<HelloWorkflow.Rendering> =
bindViewBinding(HelloGoodbyeLayoutBinding::inflate) { rendering, containerHints ->
helloMessage.text = rendering.message
helloMessage.setOnClickListener { rendering.onClick }
}
```
=> Introduce a view binding function that works with AndroidX ViewBindings.

kotlin/.buildscript/android-ui-tests.gradle
This reverts commit 18e4dcfdfa110289a077b7ca9a55b1caeb07d89d.
Tests are still super flaky, so no reason to use the orchestrator, since it
increases the time each test takes to run.
=> Revert "Enable AndroidX test orchestrator to try to reduce flakiness."

swift/Workflow/Sources/RenderContext.swift, swift/Workflow/Sources/SignalWorker.swift
Wrapping them in a `Worker` prevents a race condition where multiple `Signal`s
fire on the same runloop, resulting in dropped events.
This is the first PR mentioned in #1025.
=> Add SignalWorker to wrap Signal

.github/workflows/deploy-doc-site.yml, .github/workflows/validate-documentation.yml, RELEASING.md, deploy_website.sh
This workflow is run whenever a release tag is pushed (starts with `v` prefix), or when
a pull request is made that modifies the workflow, so the changes can be validated. In
the latter case, the `deploy_website.sh` script is run in dry mode so the docs are built
but not actually deployed. This workflow re-uses the gradle artifact and bundle caches
from the Kotlin and Swift workflows, respectively.
This requires a few changes to the `deploy_website.sh` script:
- Use HTTPS instead of SSH to clone.
- Allow custom username/password to be passed in via environment variables,
so the GH Workflow can authenticate using its token.
- Enable dry runs by setting the `DRY_RUN` environment variable, so pull requests that
modify this workflow definition can still run the build steps in CI to validate …
=> Add a Github Workflow to automatically publish the doc site when release tags are pushed.

.github/workflows/kotlin.yml
Some assemble runs take ~8 minutes, which, when added to the durations of the other steps in the job, exceeds the timeout.
Also removes the `'!gh-pages'` from the push branch list, since `master` doesn't use globs it's good enough.
=> Increase CI timeout for Kotlin assemble job

.github/workflows/kotlin.yml
It doesn't seem to be any more efficient than just downloading the wrapper every time.
=> Remove gradle wrapper cache

.github/workflows/kotlin.yml
I'm an idiot, and #1062 changed the timeout for the Check job, not the Assemble job.
> Some assemble runs take ~8 minutes, which, when added to the durations of the other steps in the job, exceeds the timeout.
>
> Also removes the '!gh-pages' from the push branch list, since master doesn't use globs it's good enough.
=> Increase CI timeout for Kotlin assemble job (for real)

.github/workflows/kotlin.yml, deploy_website.sh
Gradle doesn't use the build cache by default, so we weren't actually caching any
build artifacts, just dependencies. This change turns on build caching for all
gradle invocations, and adds some logic to the kotlin workflow to wipe the build cache
before each fresh assemble run.
=> Fix Kotlin build caching.

swift/WorkflowUI/Sources/ViewControllerDescription/DescribedViewController.swift, swift/WorkflowUI/Tests/DescribedViewControllerTests.swift
Because the `DescribedViewController` wraps all view controllers used in
workflows, if it does not vend its current child's
`preferredContentSize`, it will be lost. This makes it very difficult to
create dynamic workflows that rely on self-sizing view controllers
without introducing workarounds to have the children communicate their
intended size to the parent, or by removing the convenience of the
`DescribedViewController` entirely. This change solves the issue by
having the `DescribedViewController` update its own
`preferredContentSize` to match whatever the `currentViewController` is,
and when that child's size changes.
=> Vend `preferredContentSize` through the `DescribedViewController`

swift/WorkflowUI/Sources/Container/ContainerViewController+AnyWorkflow.swift, swift/WorkflowUI/Tests/ContainerViewControllerTests.swift
Currently, we don't have an API to create a `ContainerViewController` with `AnyWorkflow` type. This adds an extension to make that possible. 
This is mostly a copy-paste from code @bencochran shared with me privately.
=> Add ContainerViewController init with AnyWorkflowConvertable

swift/Workflow/Sources/Workflow.swift, swift/WorkflowUI/Sources/Container/ContainerViewController+AnyWorkflow.swift
Essentially a “StatelessWorkflow” without that being a separate type.
#236
=> Provide empty `makeInitialState` and `workflowDidChange` when State is Void 

.gen_config.yml, Development.podspec, swift/Samples/ModalContainer/ModalContainer.podspec, swift/Samples/ModalContainer/README.md, swift/Samples/ModalContainer/Sources/ModalContainerScreen.swift, swift/Samples/ModalContainer/Sources/ModalContainerViewController.swift, swift/Samples/TicTacToe/Sources/Authentication/AuthenticationWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/ConfirmQuitScreen.swift, swift/Samples/TicTacToe/Sources/Game/ConfirmQuitWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/GameState.swift, swift/Samples/TicTacToe/Sources/Game/RunGameWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/TakeTurnsWorkflow.swift, swift/Samples/TicTacToe/Sources/Main/MainWorkflow.swift
This PR has all the changes addressing the PR i had created a few days ago. Git is not letting me reopen the earlier closed PR since i used force-push in order to fix some commit history issue. I had seen that issue before and have finally found the root cause. I do not foresee this being a problem anymore. I will add everyone's respective comments to make things easier for everyone. For reference, here's the older closed [PR](https://github.com/square/workflow/pull/1087). 
PR includes:
1. Adding ModalContainerScreen and ModalContainerViewController to open source adding a podspec file for the same.
2. Presenting modal view controller as a "confirm to quit" screen to TicTacToe app. 
3. All the PR feedback from the previous PR which i will mention at each line for reference.
=> Modal Container with Modal Sample App

Workflow.podspec, WorkflowTesting.podspec, WorkflowUI.podspec, swift/Samples/BackStackContainer/BackStackContainer.podspec, swift/Samples/ModalContainer/ModalContainer.podspec, swift/Samples/SplitScreenContainer/SplitScreenContainer.podspec
Bumped iOS deployment target of podspec files which were at 9.3 to 10.0. Development.podspec is already at 11 so we will not change it. We are keeping the rest 10.0 since we still have to support iOS 10 for SPOS
=> Bumping ios deployment target

kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt
There are obvious optimizations we'd like to make to ensure that we don't re-render when the state does not change.
=> Stops promising to re-render on noAction.

swift/WorkflowTesting/Sources/WorkflowRenderTester.swift, swift/WorkflowTesting/Tests/WorkflowRenderTesterTests.swift
This PR moves `file: StaticString = #file, line: UInt = #line` in the `render` function of `RenderTester` to the beginning of the signature. This allows us to use the assertion: part of the function as a trailing closure. 
Currently if you're writing tests using a `RenderTester`, the following throws a `Ambiguous reference to member 'render'` error:
```
let renderTester = TestWorkflow(initialText: "initial").renderTester()
renderTester.render { screen in
XCTAssertEqual("initial", screen.text)
}
```
To get it to work you would need to explicitly use the `assertion:` label 
```
let renderTester = TestWorkflow(initialText: "initial").renderTester()
renderTester.render(
assertions: { screen in
XCTAssertEqual("initial", screen.text)
}
)
```
This PR resolve this and allows us to use trailing …
=> Reorder RenderTester render arguments

swift/Samples/SampleApp/Sources/DemoWorkflow.swift, swift/Workflow/Sources/RenderContext.swift, swift/Workflow/Sources/SubtreeManager.swift, swift/Workflow/Tests/ConcurrencyTests.swift, swift/Workflow/Tests/SubtreeManagerTests.swift, swift/WorkflowTesting/Sources/WorkflowRenderTester.swift, swift/WorkflowUI/Tests/ContainerViewControllerTests.swift
This is a rebase of #1025. It removes `context.subscribe` altogether, now that we've migrated our internal clients. **This is a breaking change.**
This finishes the work on #402 / #744.
=> Remove context.subscribe

kotlin/buildSrc/src/main/java/Dependencies.kt, kotlin/samples/hello-compose-binding/src/main/java/com/squareup/sample/hellocomposebinding/HelloBinding.kt, kotlin/workflow-ui/core-compose/src/main/java/com/squareup/workflow/ui/compose/ComposeViewFactory.kt
This converts to the new modifier fluent syntax, as well as changes how updates are
sent into `bindCompose` compositions.
Previously, every time we got a rendering, we would call `setContent` on the view hosting
the composition and call `showRendering` from there. It worked, but probably wasn't the
most efficient solution (the content function isn't really changing, we just need to
pass some new data to the composition). However, in dev09, there seems to be a bug in
Compose (filed [here](https://issuetracker.google.com/issues/155106688)) that causes a crash when this is done from an input handler. So this PR changes
that mechanism to only call `setContent` at view initialization and use a `MutableState`
object to pass new renderings/`ViewEnvironment`s into the composition. This avoids the …
=> Upgrade compose to dev09.

kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/LayoutRunner.kt
PR adds the missing function reference to `inflate` in AndroidX ViewBinding doc for LayoutRunner.
Fixes #1124
Please select at least one
How was this change tested?
N/A.
This PR is a documentation fix.
=> Add missing function reference in ViewBinding doc.

.github/PULL_REQUEST_TEMPLATE.md
The PR template is causing a bit more friction than I think is necessary, so this change makes a few improvements:
- The formatting of the template required moving the commit message text, which was just a hassle. 
- Many options in the "type of change" list already exist as labels, and labels are a better tool for this (searchable).
- Documentation section was redundant with documentation checklist.
- Additional Info section was unclear - that stuff should be in the commit message anyway.
- Removed trivial items from the checklist and merged testing and general checklist
=> Trim the PR template

kotlin/.buildscript/configure-compose.gradle, kotlin/buildSrc/src/main/java/Dependencies.kt, kotlin/samples/hello-compose-binding/build.gradle.kts, kotlin/samples/hello-compose-binding/src/androidTest/java/com/squareup/sample/hellocomposebinding/HelloBindingTest.kt, kotlin/workflow-ui/core-compose/README.md, kotlin/workflow-ui/core-compose/build.gradle.kts, kotlin/workflow-ui/core-compose/src/main/java/com/squareup/workflow/ui/compose/ComposeViewFactory.kt
Dev10 finally brings support for coroutines!
This is the first compose update in a while to actually bump the compiler version
as well as the plugin version, which is why it requires a few more changes
to work.
Fixes # (issue)
Please select at least one
How was this change tested?
=> Update Compose to dev10.

.gen_config.yml, Development.podspec, swift/Samples/AlertContainer/AlertContainer.podspec, swift/Samples/AlertContainer/README.md, swift/Samples/AlertContainer/Sources/AlertContainerScreen.swift, swift/Samples/AlertContainer/Sources/AlertContainerViewController.swift, swift/Samples/TicTacToe/Sources/Authentication/AuthenticationWorkflow.swift, swift/Samples/TicTacToe/Sources/Authentication/LoadingScreen.swift, swift/Samples/TicTacToe/Sources/Authentication/LoginWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/ConfirmQuitWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/RunGameWorkflow.swift, swift/Samples/TicTacToe/Sources/Main/MainWorkflow.swift
- Added AlertContainerScreen and AlertContainerViewController to Workflow samples.
- Created a basic alert view using UIKit
- Adding alert view to TicTacToe app:
- AuthenticationWorkflow for auth failure 
- ConfirmQuitWorkflow for show a confirm again dialog
[Demo Video](https://drive.google.com/open?id=1EFCNivfqkII9bMpFWUhxWHM53O5dGrs2)
=> Adding Alert Screen to Workflow Samples

kotlin/workflow-ui/core-android/build.gradle.kts
=> Make workflow-ui-android-core declare workflow-runtime as api instead of implementation dependency.

kotlin/buildSrc/src/main/java/Dependencies.kt, kotlin/samples/tictactoe/app/build.gradle.kts, kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/workflow-ui/core-android/api/core-android.api, kotlin/workflow-ui/core-android/build.gradle.kts, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt, kotlin/workflow-ui/core-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
=> Remove RxJava2 dependency from Workflow Android UI integration.

kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/BackButtonScreen.kt, kotlin/workflow-ui/core-android/api/core-android.api, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/BindingViewRegistry.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/CompositeViewRegistry.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/ViewFactory.kt, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui/core-android/src/test/java/com/squareup/workflow/ui/BindingViewRegistryTest.kt, kotlin/workflow-ui/core-android/src/test/java/com/squareup/workflow/ui/CompositeViewRegistryTest.kt, kotlin/workflow-ui/core-android/src/test/java/com/squareup/workflow/ui/TestViewFactory.kt, kotlin/workflow-ui/core-android/src/test/java/com/squareup/workflow/ui/ViewRegistryTest.kt
`ViewRegistry` is now just responsible for returning a `ViewFactory` for a given
rendering type, as well as checking that views returned from the factory have been
correctly bound with `bindShowRendering`. `buildView` has been extracted into an
extension method on `ViewRegistry`.
This change simplifies the responsibility of each `ViewRegistry` implementation. It
also makes `ViewRegistry` more flexible for extension. For example, allows a
Compose-based `ViewFactory` to detect recursive Compose bindings and stay in Compose
instead of jumping back out into the legacy view layer every time.
=> Simplify ViewRegistry to act more like a simple map of rendering type to ViewFactory.

.github/workflows/kotlin.yml
The upload-archive action now supports globbing, so we can easily
upload all the test reports from all modules.
=> Upload android instrumentation test results from CI.

swift/Workflow/Sources/SubtreeManager.swift
Fixes #968
I didn't annotate all of the `fatalError` calls, because some of them are effectively unreachable (e.g. `AnyChildWorkflow.enableEvents()`) or are infrastructure problems not consumer problems (i.e. there may not be anything actionable on the side of the library consumer).
=> Annotate fatalError()s with Workflow type

swift/Samples/SampleApp/Sources/DemoWorkflow.swift, swift/Samples/SampleApp/Sources/RootWorkflow.swift, swift/Samples/SampleApp/Sources/WelcomeWorkflow.swift, swift/Samples/SplitScreenContainer/DemoApp/DemoWorkflow.swift, swift/Samples/TicTacToe/Sources/Authentication/AuthenticationWorkflow.swift, swift/Samples/TicTacToe/Sources/Authentication/LoginWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/ConfirmQuitWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/RunGameWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/TakeTurnsWorkflow.swift, swift/Samples/TicTacToe/Sources/Main/MainWorkflow.swift, swift/Workflow/Sources/Workflow.swift, swift/Workflow/Tests/AnyWorkflowTests.swift, swift/Workflow/Tests/ConcurrencyTests.swift, swift/Workflow/Tests/SubtreeManagerTests.swift, swift/Workflow/Tests/WorkflowHostTests.swift, swift/Workflow/Tests/WorkflowNodeTests.swift, swift/WorkflowTesting/Tests/WorkflowActionTesterTests.swift, swift/WorkflowTesting/Tests/WorkflowRenderTesterTests.swift, swift/WorkflowUI/Tests/ContainerViewControllerTests.swift
`workflowDidChange` is hardly ever used. Providing a default implementation to reduce unnecessary boilerplate.
=> Provide default workflowDidChange implementation

kotlin/gradle/wrapper/gradle-wrapper.properties
Notably, 6.4.1 fixes a bug where daemons weren't shared between IDE and CLI.
=> Upgrade gradle to latest version.

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Addressing [#959](https://github.com/square/workflow/issues/959)
=> Make expected workers optional in RenderTester

Workflow.podspec
`pod spec lint` was failing with the error:
> xctest encountered an error (Failed to load the test bundle. (Underlying error: The bundle “Workflow-Unit-Tests” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. dlopen_preflight(DerivedData/App-fjnxhlsdrldlhtbvawtgcubjgass/Build/Products/Debug-iphonesimulator/Workflow-Unit-Tests.xctest/Workflow-Unit-Tests): Library not loaded: @rpath/libswiftos.dylib
*Note*: This PR is targeting the `release-v0.28.x` branch, as we should probably tag a `v0.28.1`.
=> Fix missing libswiftos.dylib

swift/Samples/BackStackContainer/Sources/BackStackContainer.swift, swift/Samples/BackStackContainer/Sources/BackStackScreen.swift, swift/Samples/BackStackContainer/Sources/ScreenWrapperViewController.swift, swift/Samples/TicTacToe/Sources/Authentication/AuthenticationWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/RunGameWorkflow.swift, swift/Samples/TicTacToe/Sources/Main/MainWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/Edit/TodoEditWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/List/TodoListWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/Edit/TodoEditWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/List/TodoListWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/TodoWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/RootWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/Edit/TodoEditWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/List/TodoListWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/TodoWorkflow.swift, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/TodoWorkflowTests.swift, swift/WorkflowUI/Sources/Screen/AnyScreen/AnyScreen.swift
Part of #1046
**Pros**
* This makes `BackStackScreen` more consistent with our other containers.
* For back stacks that only have one screen type (e.g. single-screen stacks), there isn't an additional `AnyScreen` wrapping layer anymore.
* Potentially easier testing — you can get at the underlying type without having to cast.
**Cons**
* This creates more work when concatenating multiple back stacks together (which could arguably be pushed into the concatenation API (e.g. `appending<T: Screen>(_ other: BackStack<T>) -> BackStackScreen<AnyScreen>`)).
* More work is required to wrap your screen in an `AnyScreen` before adding it to a `BackStackScreen<AnyScreen>`. ~This could be mitigated by adding helper functions (e.g. in `Screen`: `func asAnyScreen() -> AnyScreen`); otherwise you have to …
=> Make BackStackScreen generic

.hooks/pre-commit, swift/Samples/AlertContainer/Sources/AlertContainerViewController.swift, swift/Samples/BackStackContainer/Sources/BackStackContainer.swift, swift/Samples/ModalContainer/Sources/ModalContainerViewController.swift, swift/Samples/SampleApp/Sources/CrossFadeContainer.swift, swift/Samples/SampleApp/Sources/DemoScreen.swift, swift/Samples/SampleApp/Sources/ReversingWorkflow.swift, swift/Samples/SampleApp/Sources/RootWorkflow.swift, swift/Samples/SampleApp/Sources/WelcomeScreen.swift, swift/Samples/SplitScreenContainer/DemoApp/BarScreen.swift, swift/Samples/SplitScreenContainer/DemoApp/FooScreen.swift, swift/Samples/SplitScreenContainer/SnapshotTests/SplitScreenContainerScreenSnapshotTests.swift, swift/Samples/SplitScreenContainer/Sources/SplitScreenContainerViewController.swift, swift/Samples/TicTacToe/Sources/Authentication/LoadingScreen.swift, swift/Samples/TicTacToe/Sources/Authentication/TwoFactorScreen.swift, swift/Samples/TicTacToe/Sources/Game/ConfirmQuitScreen.swift, swift/Samples/TicTacToe/Sources/Game/GamePlayScreen.swift, swift/Samples/TicTacToe/Sources/Game/NewGameScreen.swift, swift/Samples/TicTacToe/Sources/Main/MainWorkflow.swift
I took a quick pass through the Samples and updated it based on recent API changes. 
Changes:
* `screenDidChange` gets called on `init`. Hence, we don't need an `update()` method that gets called from `init` and from `screenDidChange`. Removing `update` and where possible `init`.
* When `State = Void` we have default conformances for `makeInitialState` and `workflowDidChange`. 
Will be good to discuss any change that folks might feel are not purely positive.
=> Minor sample cleanups

.buildscript/deploy_snapshot.sh, .github/workflows/kotlin.yml, .github/workflows/release.yml, .github/workflows/swift.yaml, RELEASING.md, docs/faq.md, docs/tutorial/index.md
=> Rename all references to master branch to trunk in build scripts and documentation.

kotlin/workflow-testing/api/workflow-testing.api, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Note the base is https://github.com/square/workflow/pull/1172. I had made some changes to documentation earlier but missed a spot
=> Allowing opt-out of lenient worker expectations

swift/Workflow/Sources/Debugging.swift, swift/Workflow/Sources/Lifetime.swift, swift/Workflow/Sources/RenderContext.swift, swift/Workflow/Sources/SubtreeManager.swift, swift/Workflow/Tests/SubtreeManagerTests.swift, swift/Workflow/Tests/WorkflowNodeTests.swift, swift/WorkflowTesting/Sources/RenderExpectations.swift, swift/WorkflowTesting/Sources/WorkflowRenderTester.swift, swift/WorkflowTesting/Tests/WorkflowRenderTesterTests.swift
Introduces a `SideEffect` hook that will be used to perform the functionality currently provided by `Worker`s. 
This is a subset of @bencochran's implementation in the [bc/guwt-prototype](https://github.com/square/workflow/compare/bc/guwt-prototype) branch.
=> Introduce SideEffect #1021

.github/workflows/release.yml, docs/faq.md, docs/tutorial/index.md
In the last week, the discussion around git branch naming seems to have
settled around "main" being the most popular choice. Github is even
changing their default branch name to this.
=> Rename trunk branch to main.

.github/workflows/update-docs.yml, deploy_website.sh
This creates a new GitHub Action that can be manually run to generate the documentation for Kotlin and Swift and publishes the resulting site to a defined branch. (I didn't want to auto-merge into `gh-pages` quite yet.)
We will need to take some time to reconcile this against the existing `deploy_website.sh` script.
=> Create GitHub action to manually publish documentation

docs/tutorial/building-a-workflow.md
This was missed when all the Worker API changes were made earlier in the year.
=> Update Worker tutorial to match updated API

docs/faq.md
=> Update Elm and React comparison Table

mkdocs.yml
Configure the [`edit_uri`](https://www.mkdocs.org/user-guide/configuration/#edit_uri) to specify `main` as the repository convergence branch rather than the default of `master`. This resolves a 404 error when selecting the edit icon for any page within the [documentation site](https://square.github.io/workflow/).
=> docs: configure edit URI for hosted documentation

docs/glossary.md
It was pretty unreadable with no paragraph breaks. The definition list still requires some judicious use of `<br/>`, but it's a clear improvement I think.
=> Changes the Glossary table to a definition list.

requirements.txt
Requires python 3.7, GHA is on 3.6
=> Downgrade to mkdocs-material 8.2.12

requirements.txt
8.2.12 wants a version of pymdown-extensions that GHA can't provide.
=> Downgrade mkdocs to 8.2.11

docs/glossary.md
Using &lt;dd> botched all the 'graph and 'list markdown in the glossary entries. I think I missed it b/c I previewed as github markdown?
I made no effort at all to format this well -- life is too short for &lt;/p> and &lt;/li>.
=> Fixes glossary formatting again.

docs/userguide/comparison.md, docs/userguide/core-workflow.md, docs/userguide/ui-concepts.md
"Separation of Concerns," "What's a Screen?" and a TBD for "Composition and Navigation" that at least links to something.
Also deletes `comparison.md` because it would be redundant with existing FAQ entries, unnecessary.
=> UI Concepts pt. 1

docs/glossary.md
MarkDown hates &lt;dl> lists, so stop trying to use them. Now the glossary entries are headings, and we're able to use normal markdown everywhere else. Biggest benefit, and the thing that drove me to do this, is that we can link directly to each entry this way.
Also adds some intra-glossary links. Did not go too crazy, e.g. State and Output get mentioned so many times that linking each reference seemed silly.
=> Another Glossary overhaul, no more HTML

docs/userguide/concepts.md
Within the `Workflow Core -> Composing Workflows` [documentation](https://square.github.io/workflow/userguide/concepts/#composing-workflows), a minor error can be noticed in the last paragraph. It appears that an incorrect class name has been used to refer to the parent workflow, which is contrary to the documentation context and understanding. Based on my understanding, the parent workflow should be correctly identified as `EmailBrowserWorkflow`, rather than `EmailInboxWorkflow`. 
The paragraph I am referring to is:
> Whenever such a [Workflow Action cascade](https://square.github.io/workflow/glossary#action-cascade) fires, the root Workflow is asked for a new Rendering. Just as before, EmailInboxWorkflow delegates to its two children for their Renderings, this time providing the new …
=> Fix incorrect workflow parent name used in `Workflow Core` documentation

.github/workflows/update-docs.yml, RELEASING.md, deploy_website.sh, mkdocs.yml
Swift API docs are now being published at [square.github.io/workflow-swift/documentation](https://square.github.io/workflow-swift/documentation) using Apple's DocC generator. This PR links to that and removes all the scripting for embedding Swift docs that I could find.
=> Link to new Swift API docs
