viewbuilder-android/build.gradle, viewbuilder-rx2/build.gradle
=> Remove maven publish plugin from sample modules.

sample-android-app/build.gradle, viewbuilder-android/build.gradle, viewbuilder-android/gradle.properties, viewbuilder-rx2/build.gradle, viewbuilder-rx2/gradle.properties
PR #36 was bad. This should be the last blocker to 0.4.0.
=> Add configuration to publish viewbuiler artifacts.

.gitignore
=> Add .idea folder and .iml file to .gitignore

sample-game-common/src/test/java/com/squareup/sample/tictactoe/TakeTurnsReactorTest.kt, sample-game-common/src/test/java/com/squareup/sample/tictactoe/TurnTest.kt, workflow-core/src/test/java/com/squareup/workflow/ComposedReactorIntegrationTest.kt, workflow-core/src/test/java/com/squareup/workflow/ReactorAsWorkflowIntegrationTest.kt, workflow-core/src/test/java/com/squareup/workflow/WorkerTest.kt, workflow-core/src/test/java/com/squareup/workflow/WorkflowPoolTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/ComposedReactorIntegrationTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/CoroutineEventChannelTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/ReactorAsWorkflowIntegrationTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/UncaughtExceptionsTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkerIntegrationTest.kt, workflow-rx2/src/test/java/com/squareup/workflow/rx2/WorkflowPoolIntegrationTest.kt
Per title
Closes issue: https://github.com/square/workflow/issues/47
=> Use backsticks on test names

workflow-core/src/main/java/com/squareup/workflow/Reactor.kt, workflow-rx2/src/main/java/com/squareup/workflow/rx2/Reactor.kt
Originally in #48, which I merged into a PR branch instead of master because I was in a rush.
=> Ensure all workflow coroutines are named, to help with debugging.

sample-game-common/src/main/java/com/squareup/sample/tictactoe/RunGameReactor.kt
Otherwise it just hangs out in the global space and
the result is picked up the next time we enter this
state. Confusing, bad example.
(That'll be less of a landmine when #90 is fixed.)
=> Restores the `abandonWorker()` call in `RunGameReactor`.

sample-game-common/build.gradle, sample-game-common/src/test/java/com/squareup/sample/tictactoe/TakeTurnsReactorTest.kt, workflow-test/build.gradle, workflow-test/gradle.properties, workflow-test/src/main/java/com/squareup/workflow/rx2/TestUtils.kt
=> Add Reactor test helper functions #85

sample-android-app/src/main/java/com/squareup/sample/authgameapp/ShellActivity.kt
=> Tweaks ShellActivity sample to use toCompletable() properly.

kotlin/samples/tictactoe/android-app/src/main/AndroidManifest.xml, kotlin/samples/tictactoe/android-app/src/main/java/com/squareup/sample/authgameapp/MainActivity.kt, kotlin/samples/tictactoe/android-app/src/main/java/com/squareup/sample/authgameapp/MainComponent.kt, kotlin/samples/tictactoe/android-app/src/main/java/com/squareup/sample/authgameapp/MainReactor.kt, kotlin/samples/tictactoe/android-app/src/main/java/com/squareup/sample/authgameapp/MainRenderer.kt, kotlin/samples/tictactoe/android-app/src/main/java/com/squareup/sample/authgameapp/MainState.kt, kotlin/samples/tictactoe/android-app/src/main/res/values/strings.xml, kotlin/samples/tictactoe/android-app/src/test/java/com/squareup/sample/authgameapp/MainReactorTest.kt, kotlin/samples/tictactoe/game-android/src/main/java/com/squareup/sample/tictactoe/android/GameOverCoordinator.kt, kotlin/samples/tictactoe/game-android/src/main/java/com/squareup/sample/tictactoe/android/GamePlayCoordinator.kt, kotlin/samples/tictactoe/game-android/src/main/res/layout/game_play_layout.xml
Uses the stock Toolbar widget, and changes the strange "Shell" terminology to "Main" -- MainActivity, MainReactor, etc.
=> Sample app tweaks

.travis.yml
I used Travis CLI to encrypt a key for deployment, looks like it reformatted the file along the way.
=> Auto-deploy gh-pages from master

Workflow.podspec, kotlin/gradle.properties, swift/CHANGELOG.md
This is a kotlin-only release that bumps the kotlin version to 1.2.71.
=> Releasing v0.8.1.

swift/Workflow/Tests/WorkflowNodeTests.swift
Because the tests were based upon sleeping for the right amount
of time they ended up flaking. The expectations should shorten the time
that we wait, while also giving us longer if the CI system happens
to be a bit slower.
=> Switch async workflow node tests to using expectations instead of spinning the runloop

kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflows.kt
=> Make a StatelessWorkflow typealias and a hideState() extension function.

docs/src/markdown/documentation/faq.md
Reworded to be more diplomatic
=> Fix some words

kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowContext.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/LifetimeTracker.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/RealWorkflowContext.kt, kotlin/workflow-host/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/LifetimeTrackerTest.kt, kotlin/workflow-host/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTesting.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/CompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/SuspendingSubscriptionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowTesterTest.kt
=> Add tests for snapshotting.

README.md
I also indented the list because it looks so much better in plaintext.
=> Added link to Android Dialogs series

swift/Workflow/Sources/WorkflowContext.swift
This allows for things like
```swift
let sink = context.makeSink(of: String.self) { string, state in
state.customerName = string
return nil
}
```
and
```swift
context.awaitResult(for: AccountLoadingWorker()) { account, state in
state = .loaded(account: account)
}
```
=> Add convenience extensions for makeSink and awaitResult

.travis.yml
=> Disable WorkflowUI Xcode 10.1 shard because it's broken.

kotlin/workflow-core/src/main/java/com/squareup/workflow/util/KTypes.kt
This changes uses Kotlin reflection's types, but doesn't rely on its factory functions to create them.
=> Workaround #211 by implementing KType ourselves.

kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/CoroutineEventChannelTest.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/WorkflowOperatorsTest.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/panel/PanelContainer.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/gameworkflow/TakeTurnsReactorTest.kt
These have been annoying the hell out of me.
=> Suppress valid deprecation and unchecked cast warnings.

.travis.yml
=> Disable broken Swift Workflow 10.1 shard. (Workaround #223)

kotlin/build.gradle, kotlin/samples/tictactoe/android/build.gradle
Some had the version suffix, most didn't.
=> Makes version names consistent

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt
Don't know how I merged it this way. :( #246 tracks the need to get tests
around this, which will not be any fun at all.
Closes #244.
=> Fixes broken Parcellable implementation in ModalContainer

kotlin/build.gradle, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowViewModel.kt
Instead of Rx's android main scheduler.
Closes #252.
=> Use kotlinx-coroutines-android and Dispatchers.Main

kotlin/CHANGELOG.md, swift/CHANGELOG.md
Updates changelogs in preparation for releasing 0.12.0
=> Update changelogs for 0.12.0

kotlin/gradle/wrapper/gradle-wrapper.properties
=> Upgrade Gradle to latest version.

kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RenderContexts.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/RenderContextsTest.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/SubscriptionsTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/ChannelSubscriptionsIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/CompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowTesterTest.kt
=> Rename WorkflowContext to RenderContext.

docs/swift/building-a-workflow.md, swift/Samples/SampleApp/Configuration/Info.plist, swift/Samples/SampleApp/Podfile.lock, swift/Samples/SampleApp/SampleApp.xcodeproj/project.pbxproj, swift/Samples/SampleApp/SampleApp.xcodeproj/xcshareddata/xcschemes/SampleApp.xcscheme, swift/Samples/SampleApp/Sources/AppDelegate.swift, swift/Samples/SampleApp/Sources/CrossFadeContainer.swift, swift/Samples/SampleApp/Sources/DemoScreen.swift, swift/Samples/SampleApp/Sources/DemoWorkflow.swift, swift/Samples/SampleApp/Sources/ReversingWorkflow.swift, swift/Samples/SampleApp/Sources/RootWorkflow.swift, swift/Samples/SampleApp/Sources/ViewController.swift, swift/Samples/SampleApp/Sources/WelcomeScreen.swift, swift/Samples/SampleApp/Sources/WelcomeWorkflow.swift
This is an overly simple sample, but uses the same concepts and names in the current documentation.
=> Add swift sample app modeled against docs

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
This was the previous behavior of all the single/optional-output
`RenderContext` extensions, it's much more convenient this way.
=> Fix onWorkerOutput to noop on finish instead of throw.

kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/Board.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameState.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflowTest.kt
* Fixes resuming of Tic Tac Toe after maybe quit dialog -- Closes #382.
* Fixes draw result.
=> Tic Tac Toe bug fixes. (OMFG)

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt
=> Allows WorkflowLayout to work from any stream of renderings.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt
=> Fix snapshots of a non-flat tree being taken too late.

kotlin/build.gradle, kotlin/gradle.properties, kotlin/samples/hello-workflow-fragment/build.gradle, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragmentActivity.kt, kotlin/samples/hello-workflow/build.gradle, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt, kotlin/samples/tictactoe/android/build.gradle, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/authworkflow/SecondFactorLayoutRunner.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/gameworkflow/GameOverLayoutRunner.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/gameworkflow/GamePlayLayoutRunner.kt, kotlin/samples/tictactoe/android/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/tictactoe/android/src/main/res/layout-land/game_play_layout.xml, kotlin/samples/tictactoe/android/src/main/res/layout/game_play_layout.xml, kotlin/samples/tictactoe/android/src/main/res/layout/second_factor_layout.xml, kotlin/samples/todo-android/todo-android-app/build.gradle, kotlin/samples/todo-android/todo-android-app/src/main/java/com/squareup/sample/mainactivity/ItemListView.kt, kotlin/samples/todo-android/todo-android-app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/todo-android/todo-android-app/src/main/java/com/squareup/sample/mainactivity/TodoEditorLayoutRunner.kt, kotlin/samples/todo-android/todo-android-app/src/main/res/layout/todo_editor_layout.xml, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/AlertContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt
Per title.
It also opens the way for: https://github.com/square/workflow/issues/51
Closes issue: https://github.com/square/workflow/issues/50, https://github.com/square/workflow/issues/66
=> Migrate to AndroidX

kotlin/build.gradle
Mostly followed the instructions here:
https://proandroiddev.com/publishing-a-maven-artifact-3-3-step-by-step-instructions-to-mavencentral-publishing-bd661081645d
=> Bumped maven publish plugin to latest version to release to Sonatype OSS.

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt
This is to prevent logcat noise about leaked windows. Mind you, nothing bad
was actually happening. The windows still got closed. We just got scolded for
being presumptuous enough to ask the runtime to do us a tiny favor.
Closes #51.
=> Set up a teardown hook for dialogs.

kotlin/build.gradle, kotlin/legacy/legacy-workflow-rx2/build.gradle, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/CoroutineEventChannelTest.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/ReactorAsWorkflowIntegrationTest.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/Rx2ReactorIntegrationTest.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/Rx2WorkflowPoolIntegrationTest.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/UncaughtExceptionsTest.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/WorkerIntegrationTest.kt, kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/WorkflowOperatorsTest.kt, kotlin/samples/tictactoe/android/build.gradle, kotlin/samples/tictactoe/common/build.gradle, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/gameworkflow/PlayerInfoTest.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflowTest.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt, kotlin/samples/todo-android/todo-android-app/build.gradle, kotlin/samples/todo-android/todo-android-common/build.gradle, kotlin/workflow-ui-core/build.gradle, kotlin/workflow-ui-core/src/test/java/com/squareup/workflow/ui/CompatibleTest.kt, kotlin/workflow-ui-core/src/test/java/com/squareup/workflow/ui/NamedTest.kt
=> Migrate from AssertJ to Truth, upgrade to Truth 1.0.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LaunchWorkflowTest.kt
This happens anytime something inside the workflow tree throws a `CancellationException`.
Fixes #464. Blocks upgrading internally.
=> Ensure the outer workflow runtime scope gets cancelled when the workflow loop cancels itself.

kotlin/build.gradle, kotlin/gradle.properties, kotlin/legacy/legacy-workflow-rx2/build.gradle, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/AlertContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/LayoutRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalViewContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt
=> Replace support annotations with AndroidX annotations.

README.md
=> Update maven artifact names in README.

.travis.yml
Merged #483 too soon. Will actually verify the Travis log this time…
=> Fixed travis config for snapshot deployment

.gitignore, deploy_website.sh, kotlin/.buildscript/configure-dokka.gradle, kotlin/build.gradle, kotlin/workflow-core/build.gradle, kotlin/workflow-runtime/build.gradle, kotlin/workflow-rx2/build.gradle, kotlin/workflow-testing/build.gradle, kotlin/workflow-ui-android/build.gradle, kotlin/workflow-ui-core/build.gradle, mkdocs.yml
Don't merge this until #481 lands.
=> Configure deploy_website to publish kdocs.

docs/css/app.css, mkdocs.yml
Copied from OkHttp as suggested by @swankjesse in
https://github.com/square/workflow/pull/481#pullrequestreview-264500149
Old:
New:
Diff overlaid:
=> Update docs to use a Square font.

.markdownlint.rb, .travis.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, RELEASING.md, docs/concepts.md, docs/faq.md, docs/overview.md, docs/swift/adding-workflow-to-a-project.md, docs/swift/building-a-view-controller-from-screen.md, docs/swift/building-a-workflow.md, docs/swift/index.md, docs/swift/tooling.md, docs/swift/using-a-workflow-for-ui.md, lint_docs.sh
Includes a CI job!
Run `./lint_docs.sh` to run locally.
=> Add linting for our documentation and fix existing errors.

mkdocs.yml
=> Added social media links to website.

.gitignore, .travis.yml, Package.swift, Workflow.podspec, WorkflowTesting.podspec, WorkflowUI.podspec, swift/Samples/SampleApp/Sources/RootWorkflow.swift, swift/Workflow/Sources/AnyWorkflowConvertible.swift, swift/Workflow/Sources/Worker.swift, swift/Workflow/Sources/Workflow.swift, swift/Workflow/Sources/WorkflowNode.swift, swift/WorkflowTesting/Sources/WorkflowActionTester.swift, swift/WorkflowTesting/Tests/WorkflowActionTesterTests.swift
@davidapgar @bencochran are we ready to move to Swift 5?
Feels great to get rid of all the `import Result` lines!
=> Update to Xcode 10.2/Swift 5.0

swift/WorkflowTesting/Sources/RenderExpectations.swift, swift/WorkflowTesting/Sources/WorkflowRenderTester.swift, swift/WorkflowTesting/Tests/WorkflowRenderTesterTests.swift
Closes #438
Adds support to validated a workflow has a child in render, as well as that it outputs
=> Expect child workflows and outputs in render tester

kotlin/build.gradle
Changelog: https://square.github.io/okio/changelog/#version-230
=> Upgrade Okio to latest version (2.3.0).

kotlin/build.gradle, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt
Changelog: https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.0-rc2
=> Upgrade coroutines to latest RC2.

kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt, kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/AiWorkflow.kt, kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/GameWorkflow.kt, kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/BlinkingCursorWorkflow.kt, kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/HelloTerminalWorkflow.kt, kotlin/samples/hello-terminal/todo-terminal-app/src/main/java/com/squareup/sample/hellotodo/EditTextWorkflow.kt, kotlin/samples/hello-terminal/todo-terminal-app/src/main/java/com/squareup/sample/hellotodo/TodoWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
=> Rename onWorkerOutput to runningWorker (and friends).

kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloFragmentLayoutRunner.kt, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloLayoutRunner.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt
Vestigial  event snipped, less ViewRegistry instantiation.
=> Tidies Hello samples.

swift/Samples/BackStackContainer/BackStackContainer.podspec, swift/Samples/BackStackContainer/README.md, swift/Samples/BackStackContainer/Sources/BackStackContainer.swift, swift/Samples/BackStackContainer/Sources/BackStackScreen.swift, swift/Samples/BackStackContainer/Sources/ScreenWrapperViewController.swift, swift/Samples/TicTacToe/.gitignore, swift/Samples/TicTacToe/Configuration/Info.plist, swift/Samples/TicTacToe/Podfile, swift/Samples/TicTacToe/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json, swift/Samples/TicTacToe/Resources/Assets.xcassets/Contents.json, swift/Samples/TicTacToe/Resources/Base.lproj/LaunchScreen.storyboard, swift/Samples/TicTacToe/Sources/AppDelegate.swift, swift/Samples/TicTacToe/Sources/Authentication/AuthenticationService.swift, swift/Samples/TicTacToe/Sources/Authentication/AuthenticationWorkflow.swift, swift/Samples/TicTacToe/Sources/Authentication/LoadingScreen.swift, swift/Samples/TicTacToe/Sources/Authentication/LoginScreen.swift, swift/Samples/TicTacToe/Sources/Authentication/LoginWorkflow.swift, swift/Samples/TicTacToe/Sources/Authentication/TwoFactorScreen.swift, swift/Samples/TicTacToe/Sources/Game/Board.swift, swift/Samples/TicTacToe/Sources/Game/GamePlayScreen.swift, swift/Samples/TicTacToe/Sources/Game/NewGameScreen.swift, swift/Samples/TicTacToe/Sources/Game/RunGameWorkflow.swift, swift/Samples/TicTacToe/Sources/Game/TakeTurnsWorkflow.swift, swift/Samples/TicTacToe/Sources/Main/MainWorkflow.swift, swift/Samples/TicTacToe/TicTacToe.xcodeproj/project.pbxproj, swift/Samples/TicTacToe/TicTacToe.xcodeproj/project.xcworkspace/contents.xcworkspacedata, swift/Samples/TicTacToe/TicTacToe.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, swift/Samples/TicTacToe/TicTacToe.xcworkspace/contents.xcworkspacedata, swift/Samples/TicTacToe/TicTacToe.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Also includes an example of how one might build a back stack container.
=> Add TicTacToe Sample

README.md
We're really not experimental any more.
=> Updates README.md to be less redundant and less qualified.

kotlin/build.gradle
This is just a bugfix release.
Changelog: https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.1
=> Upgrade coroutines to latest version (1.3.1).

kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/GameWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt, kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt, kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/RxWorkersTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
=> Remove key from TypedWorker and helpers that use it.

kotlin/legacy/legacy-workflow-rx2/src/main/java/com/squareup/workflow/legacy/rx2/Reactor.kt
Trying to debug old reactors and keep seeing "java"
=> Print actual class name instead of just "java"

kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/BoardLoaderWorker.kt, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt
First part of #585.
Depends on #630.
=> Add a game over screen to the dungeon sample.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowDiagnosticListener.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
Missed this in #628 (25c3697ac2d3d21da2d6607852d139d2b6abaf54).
Also cleaned up some warnings and obsolete names.
=> Added missing documentation to WorkflowDiagnosticListener.

README.md
=> Fix lint failure on README broken by #642.

kotlin/.idea/misc.xml, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/GameLayoutRunner.kt, kotlin/samples/dungeon/app/src/main/res/layout/game_layout.xml, kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/AiWorkflow.kt, kotlin/workflow-tracing/src/test/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListenerTest.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowViewStub.kt
Updates a view if it's compatible with a given rendering,  otherwise replaces
it with one that is. Makes it much simpler to write custom containers.
=> Introduces ViewRegistry.updateView.

swift/Samples/TicTacToe/Sources/Authentication/AuthenticationWorkflow.swift, swift/Samples/TicTacToe/Sources/Authentication/LoginWorkflow.swift, swift/Samples/Tutorial/Tutorial1.md
Additional fixes for #655 
- Updates TicTacToe sample app
- Added link to Xcode templates when these are referenced in the tutorial.
=> Further updates to Swift samples

.travis.yml, swift/Samples/TicTacToe/Podfile, swift/Samples/TicTacToe/Tests/Info.plist, swift/Samples/TicTacToe/Tests/TicTacToeTests.swift, swift/Samples/TicTacToe/TicTacToe.xcodeproj/project.pbxproj, swift/Samples/TicTacToe/TicTacToe.xcodeproj/xcshareddata/xcschemes/TicTacToe.xcscheme
Just an empty test bundle to make `xcodebuild test` work on Travis to make sure things stay compilable.
=> Swift: Add CI for the TicTacToe sample

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt, kotlin/workflow-testing/build.gradle, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/TestRender.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
=> Make testing infra run double render passes to suss out side effect code in render methods.

kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt
=> Fix red master after the merge-when-green bot incorrectly merged a PR before any CI had finished.

README.md
Not sure if this is a good idea, I haven't seen many other projects do this.
=> Add contact info to README.

kotlin/gradle/wrapper/gradle-wrapper.properties, kotlin/gradlew, kotlin/gradlew.bat
`./gradlew wrapper --gradle-version=5.6.3 --distribution-type=all`
=> Update gradle to 5.6.3.

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
=> Restore `testFromState`.

kotlin/build.gradle, kotlin/workflow-testing/build.gradle, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTestResult.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/TestRender.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/DeprecatedRenderTesterTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
=> Proposal: New render testing API for kotlin.

kotlin/build.gradle
Discussion: https://workflow-community.slack.com/archives/CHTFPR277/p1572980514086900
=> Inline dependency version numbers so Dependabot can update them.

kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/Lifecycles.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt
=> Make `lifecycleOrNull` public.

kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
=> Fix RenderTester not checking worker keys.

kotlin/build.gradle
Changelog: https://github.com/JetBrains/kotlin/blob/1.3.60/ChangeLog.md
Closes #748 and closes #749.
=> Upgrade Kotlin and libraries to 1.3.60.

kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt
=> Add variance to StatelessWorkflow type parameters.

kotlin/samples/containers/app-poetry/src/main/java/com/squareup/sample/poetryapp/PoetryActivity.kt, kotlin/samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/MainActivity.kt, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/EditableListActivity.kt, kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ContainerHints.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt, kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt, kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
This allows activities / fragments to pass arbitrary information down the view system. (I had intended to update one of the samples to take advantage, but not of them really needed it.)
Closes #796
=> Activity can provide ContainerHints

.travis.yml
A recent emulator update breaks a few CI projects. This PR applies a fix suggested by Google: https://issuetracker.google.com/issues/145622251#comment33
Fixes #759.
=> Fix emulators

kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/PoemWorkflow.kt, kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt, kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/PlayerWorkflow.kt, kotlin/samples/dungeon/timemachine-shakeable/src/main/java/com/squareup/sample/timemachine/shakeable/ShakeableTimeMachineWorkflow.kt, kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt, kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/AppWorkflow.kt, kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/editablelistworkflow/EditableListWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt, kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt, kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoEditorWorkflow.kt, kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Sink.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowUpdateDebugInfo.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt, kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt, kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
=> Make RenderContext itself a Sink.

kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/Sink.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt, kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowUpdateDebugInfo.kt
=> Fix docs made incorrect by d34372bd.

kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/TimeMachineAppWorkflow.kt, kotlin/samples/dungeon/timemachine/src/main/java/com/squareup/sample/timemachine/TimeMachineWorkflow.kt, kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt
And uses it in the dungeon sample. Closes #860.
=> Fixes StatelessWorkflow.action.

kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt
=> Fix racy broken WorkerStressTests.

kotlin/gradle/wrapper/gradle-wrapper.properties
```
./gradlew wrapper --gradle-version=6.1 --distribution-type=all
```
=> Upgrade gradle to 6.1.

kotlin/build.gradle, kotlin/workflow-ui-android/build.gradle
Related to #905 
Added explicit dependencies on androidx.fragment and androidx.activity to simplify dropping appcompat
=> Added explicit AndroidX dependencies

kotlin/.idea/misc.xml
This reverts commit 53979140c741be254f7f6de9295c4aa500e65cdf.
My work laptop now insists on reverting this, so I think this was only ever
a problem on my personal machine.
=> Revert "Accept the change to .idea/misc.xml that AS 4 insists on making."

kotlin/gradle.properties
=> Fix unresolved merge conflicts introduced in 99ffd78b.

kotlin/build.gradle
Changelog: https://github.com/JLLeitschuh/ktlint-gradle/blob/master/CHANGELOG.md#920---2020-02-10
=> Update ktlint gradle plugin to 9.2.0.

.travis.yml
Done on master in https://github.com/square/workflow/commit/c28c3ad6776b89fa281ded561048e0ae37b52258
Fixes #951.
=> Bump python version for static site shard on release branch

kotlin/build.gradle, kotlin/workflow-ui/core-compose/build.gradle
Release notes:
- https://developer.android.com/jetpack/androidx/releases/compose#0.1.0-dev05
- https://developer.android.com/jetpack/androidx/releases/ui#0.1.0-dev05
=> Upgrade Compose to dev05.

kotlin/build.gradle, kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowDiagnosticListenerIntegrationTest.kt, kotlin/workflow-tracing/src/test/resources/com/squareup/workflow/diagnostic/tracing/expected_trace_file.txt
First commit pulls coroutines version number back out into a variable (dependabot can't automatically update them all at once anyway). Second commit is the actual update.
=> Upgrade coroutines libraries to 1.3.4.

.travis.yml
=> Disable Android UI tests because they're too flaky.

.gitignore, deploy_website.sh, mkdocs.yml
Also fixes some other issues with the deployment script.
=> Update mkdocs config with new Kotlin UI module structure.

.travis.yml, kotlin/samples/dungeon/app/build.gradle
Re-enabled the android UI test shard.
=> Add back in the config that the dungeon crawler UI test needs to skip fake loading.

README.md
As documented [here](https://kotlinlang.slack.com/archives/C2YH04E3S/p1571313373000900).
=> Add kotlin slack badge to README.

README.md
Also moves the kotlinlang badge down to the Kotlin section.
=> Add Github Actions badges to README

.github/workflows/validate-documentation.yml
The workflow name is also more consistent now with the deploy site workflow.
=> Improve naming in validate-documentation workflow

kotlin/.buildscript/android-sample-app.gradle, kotlin/samples/containers/app-poetry/build.gradle.kts, kotlin/samples/containers/app-raven/build.gradle.kts, kotlin/samples/containers/hello-back-button/build.gradle.kts, kotlin/samples/dungeon/app/build.gradle.kts, kotlin/samples/hello-compose-binding/build.gradle.kts, kotlin/samples/hello-workflow-fragment/build.gradle.kts, kotlin/samples/hello-workflow/build.gradle.kts, kotlin/samples/recyclerview/build.gradle.kts, kotlin/samples/tictactoe/app/build.gradle.kts, kotlin/samples/todo-android/app/build.gradle.kts
Taking a stab at [#971 ](https://github.com/square/workflow/issues/971)
=> Common sample app gradle config

.github/workflows/deploy-doc-site.yml, .github/workflows/swift.yaml, swift/Workflow/Sources/AnyWorkflowConvertible.swift, swift/Workflow/Tests/ConcurrencyTests.swift
Updates CI configuration to Xcode 11.4
=> Bump CI to Xcode 11.4

.github/workflows/deploy-doc-site.yml, .github/workflows/validate-documentation.yml, RELEASING.md, deploy_website.sh, requirements.txt
Looked at a previously successful job to get the dependency versions that worked. 
Using CI to see if the pinned dependencies work.
=> Pin python dependencies

.buildscript/update_changelog.swift, .github/workflows/release.yml
Will be triggered by a Slack action. Currently updates and publishes from a "test" branch into a "test" release branch. Unfortunately, to test the `repository-dispatch` trigger, this will need to be merged to master.
=> Github Workflow to release Workflow version

Gemfile, Gemfile.lock, Workflow.podspec, WorkflowSwiftUI.podspec, WorkflowTesting.podspec, WorkflowUI.podspec, swift/Samples/BackStackContainer/BackStackContainer.podspec, swift/Samples/ModalContainer/ModalContainer.podspec, swift/Samples/SplitScreenContainer/SplitScreenContainer.podspec, swift/Samples/Tutorial/Frameworks/Tutorial1Complete/Tutorial1.podspec, swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Tutorial2.podspec, swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Tutorial3.podspec, swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Tutorial4.podspec, swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Tutorial5.podspec, swift/Samples/Tutorial/Frameworks/TutorialBase/TutorialBase.podspec, swift/Samples/Tutorial/Frameworks/TutorialViews/TutorialViews.podspec
* Bumps the local development versions of Cocoapods to current version.
* Bumps podspecs to 1.7.0
=> Bump Cocopods Version

.github/PULL_REQUEST_TEMPLATE.md
This is a work in progress. Feedback is greatly appreciated. 
I tried add all the information i could think of in order to understand a pull request for someone who may only be vaguely or unaware of the change. 
Areas covered:
- Description of the issue
- Type of change (This section is to understand the impact of the change)
- Documentation
- Any additional info needed
- Checklist to follow before you hit merge.
=> Adding pull request template to Workflow

.github/PULL_REQUEST_TEMPLATE.md
=> Add dependency update as a change type to the pull request template

Package.swift
=> Bump iOS version for SPM

kotlin/workflow-ui/core-android/api/core-android.api, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/WorkflowFragment.kt
=> Move WorkflowFragment initialization to onViewStateRestored.

kotlin/samples/containers/android/build.gradle.kts, kotlin/samples/containers/app-poetry/build.gradle.kts, kotlin/samples/containers/app-raven/build.gradle.kts, kotlin/samples/containers/common/build.gradle.kts, kotlin/samples/containers/hello-back-button/build.gradle.kts, kotlin/samples/containers/poetry/build.gradle.kts, kotlin/samples/dungeon/app/build.gradle.kts, kotlin/samples/dungeon/common/build.gradle.kts, kotlin/samples/dungeon/timemachine/build.gradle.kts, kotlin/samples/hello-workflow-fragment/build.gradle.kts, kotlin/samples/hello-workflow/build.gradle.kts, kotlin/samples/recyclerview/build.gradle.kts, kotlin/samples/tictactoe/app/build.gradle.kts, kotlin/samples/tictactoe/common/build.gradle.kts, kotlin/samples/todo-android/app/build.gradle.kts, kotlin/samples/todo-android/common/build.gradle.kts, kotlin/workflow-ui/backstack-android/build.gradle.kts, kotlin/workflow-ui/modal-android/build.gradle.kts
=> Remove a bunch of unused rxjava2 dependencies.

kotlin/buildSrc/src/main/java/Dependencies.kt
=> Upgrade coroutines library to latest version.

kotlin/gradle.properties
=> Add insecure checksums gradle flag to fix Nexus release.

.github/workflows/kotlin.yml
This is a weird way to do it, but it works around #1152.
=> Validate dokka in CI.

CHANGELOG.md
=> Changelog for v0.28.0.

.github/workflows/kotlin.yml
=> Explicitly pass gradle home path for caching.

README.md
=> Add README link to compose repo.

kotlin/buildSrc/src/main/java/Dependencies.kt
=> Upgrade to Kotlin 1.3.72 and AGP 4.0.0-rc01

docs/userguide/core-workflow.md, mkdocs.yml, requirements.txt
* Updates MkDocs to latest version.
* 'Globe' icon isn't available, so I just snipped it. (At least my understanding from reading https://github.com/squidfunk/mkdocs-material/issues/756#issuecomment-386797322) 
* Fixes tabs on Core Workflow Concepts page
* Fixes missing site search
* Resolves #1181
=> Update MkDocs & Fix Tabs and Search 

kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/SampleContainers.kt, kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/overviewdetail/OverviewDetailConfig.kt, kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/overviewdetail/OverviewDetailContainer.kt, kotlin/samples/containers/android/src/main/res/layout-ldrtl/overview_detail_split.xml, kotlin/samples/containers/android/src/main/res/layout/overview_detail_single.xml, kotlin/samples/containers/android/src/main/res/layout/overview_detail_split.xml, kotlin/samples/containers/android/src/main/res/values-land/layout.xml, kotlin/samples/containers/android/src/main/res/values-sw600dp/layout.xml, kotlin/samples/containers/android/src/main/res/values/layout.xml, kotlin/samples/containers/app-poetry/src/main/java/com/squareup/sample/poetryapp/PoemListLayoutRunner.kt, kotlin/samples/containers/app-poetry/src/main/java/com/squareup/sample/poetryapp/PoemsBrowserWorkflow.kt, kotlin/samples/containers/common/src/main/java/com/squareup/sample/container/overviewdetail/OverviewDetailScreen.kt, kotlin/samples/containers/common/src/test/java/com/squareup/sample/container/overviewdetail/OverviewDetailScreenTest.kt, kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/PoemWorkflow.kt, kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/StanzaLayoutRunner.kt, kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/StanzaListLayoutRunner.kt, kotlin/samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt, kotlin/samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/TodoListsViewFactory.kt, kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt
Fixes the kotlin half of #1188.
=> Rename all occurences of Master/Detail to Overview/Detail.

kotlin/workflow-ui/backstack-android/api/backstack-android.api, kotlin/workflow-ui/backstack-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt, kotlin/workflow-ui/core-android/api/core-android.api, kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt, kotlin/workflow-ui/modal-android/api/modal-android.api, kotlin/workflow-ui/modal-android/src/main/java/com/squareup/workflow/ui/modal/ModalContainer.kt
Short discussion in this issue:
https://github.com/square/workflow/issues/670
=> Extend ViewGroup in stock Kotlin Container classes

docs/tutorial/index.md
While this section is under construction and does not include Kotlin, point the reader to where they can learn more on their own.
=> Add link to Kotlin samples

deploy_website.sh, mkdocs.yml
=> Fix Kotlin Docs Deploy Script for Website

mkdocs.yml
=> Fix API Reference top link

.markdownlint.rb, docs/userguide/motivation.md
This was originally a [blog post](https://developer.squareup.com/blog/why-workflow/) by Steve Edwards.
=> Content for motivation.md.

requirements.txt
https://twitter.com/readthedocs/status/1507388916013314048
=> Recent jinja2 update broke mkdocs

docs/userguide/core-patterns.md
=> Adds one-and-done pattern.

docs/userguide/concepts.md, docs/userguide/ui-concepts.md, mkdocs.yml
And some tweaks to _Why does Workflow work this way?_
=> Typos, broken links, fussing with top level org.

deploy_website.sh, mkdocs.yml
fixes https://github.com/square/workflow-kotlin/issues/124
TODO
=> switch the Kotlin api docs to Dokka's `htmlMultiModule`

.github/workflows/release.yml, .github/workflows/update-docs.yml, .github/workflows/validate-documentation.yml
* Xcode_15.1.app
* Python 3.12.3
=> Bumps xcode, python versions as MacOS marches on
